function txt_drinks() {
	
	msg = msglang([
	
	txt("..."),
	txt("Hiiii Kaguya!"),
	txt("What happened over there? It sounded almost like a danmaku battle."),
	txt("Simply a greeting. Our resident tavernkeep is out at the moment, and I was catching up with her substitute."),
	txt("Yeah, don't worry about it. Come over to the bar, I'll get the two of you some drinks."),
	txt("Also, this isn't a tavern."),
	txt("Chiyuri leads the two to some bar stools, and steps behind the counter."),
	txt("As I said before, something light for the both of us."),
	txt("Our drinks have names, you know. Still don't remember them?"),
	txt("The fact that I don't is evidence to their quality."),
	txt("Or your alcoholism. Whatever, I already know what you mean."),
	txt("Chiyuri pushes some buttons on a machine embedded in the wall behind the bar."),
	txt("It's connected to a variety of alcohols and soft drinks via tube"),
	txt("What's that, if I may ask?"),
	txt("Some sort of drink-maker."),
	txt("Sorry, I would make 'em myself, but Kotohime here just tired me out."),
	txt("Quite modern, isn't it..."),
	txt("One of our regulars is a scientist, like those Kappa. She went-"),
	txt("And me!"),
	txt("Right, she and Kotohime went and made this."),
	txt("Are you skilled in that sort of thing, Kotohime?"),
	txt("It is from any princess' upbringing that she is to have myriad skills."),
	txt("I suppose it's out of the understanding of us common folk, isn't it."),
	txt("By the way, new girl, what did you say your name was?"),
	txt("(Ah... Chiyuri's playing with Kaguya. I'm sure she can handle it.)"),
	txt("It's Teruyo."),
	txt("Hm. Just Teruyo?"),
	txt("Yes."),
	txt("Just like Kotohime, then. Only one name."),
	txt("A beeping coming from behind Chiyuri steals the attention of the two at the bar."),
	txt("I'm starting to think even that isn't real, though."),
	txt("Chiyuri turns around to grab the now-prepared drinks, then swings back, silently placing them in front of the two customers."),
	txt("Unless you might know more?"),
	txt("Now that you mention it, I've only heard her as \"Kotohime\"."),
	txt("Any comment from the woman of the hour?"),
	txt("Kotohime had ensured her silence before Chiyuri had finished talking, already taking a deep gulp into her drink."),
	txt("...I can wait."),
	txt("Glug, glug... pah! What is a name, truly? Is it not ridiculous that-"),
	txt("Yeah, nevermind."),
	txt("...So, Miss..."),
	txt("Oh, right. Chiyuri. Chiyuri Kitashirakawa."),
	txt("If that many syllables is the alternative, one name does just fine, doesn't it?"),
	txt("Screw off. You can't even get it right."),
	txt("Oh, but I do."),
	txt("Kagu- Teruyo, I'll tell you about Chiyurii's name."),
	txt("This is a touch more aggressive an environment than I had imagined."),
	txt("We're just messing around, don't worry."),
	txt("Isn't that right, Chiyurii?"),
	txt("It sounds the damn same, but just knowing how you think you're saying it is annoying!"),
	txt("You think you're so clever."),
	txt("The difference is supposed to be that there's an extra \"i\" at the end."),
	txt("She says it's because-"),
	txt("Because there's two!"),
	txt("The girl before you is only one of the twin Chiyuri that exist!"),
	txt("I bore this truth with my own two eyes!"),
	txt("In a secluded cave, long ago, there was a battle between two nigh-identical combatants."),
	txt("One, armed with her prowess as a novice magic-practicioner in Gensokyo,"),
	txt("And the other, the obverse side; an apprentice scientist from the outside fighting with some sort of magic fascimile!"),
	txt("Is this true?"),
	txt("Basically, yeah."),
	txt("We met after that fight, actually. Both of us fought the other Chiyuri."),
	txt("Oh, my. I hadn't thought I could meet people as prestigious as incident resolvers, in this place."),
	txt("Ha ha, I suppose so. We aren't really recognized like that, though."),
	txt("Anyway, what does this have to do with your nickname?"),
	txt("Oh, well, it's like the Roman Numerals."),
	txt("II for two, since there's two of them, so ChiyurII."),
	txt("Wow. So clever and not forced at all."),
	txt("I had thought you couldn't read western script, Kotohime."),
	txt("She can't! I don't know how she learned this extremely specific information."),
	txt("I have my channels."),
	txt("I see. That is fairly amusing."),
	txt("Well-met, Chiyurii."),
	txt("God damn it, I can tell you're doing it too. Decent to meetcha, Teruyo."),
	txt("Kotohime, did you want to show her around the bar, or something?"),
	txt("We do have a goal in mind, but yes, that will do for now."),
	txt("A goal...?"),
	txt("It's reasonable, I assure you."),
	txt("That means little, but whatever. You know the rules."),
	txt("Have fun, you two."),
	
	],[
	
	txt(""),
	
	])
	
	endevent = c_null;
}