function txt_chillin() {
	
	msg = msglang([
	
	txt("Kotohime, I'm surprised you can take this so seriously."),
	txt("Do you not have your \"princessly duties\" this eve?"),
	txt("Alas, the eve has already given way to morrow."),
	txt("So it has..."),
	txt("Especially with that, will you be staying much longer, Kotohime?"),
	txt("No, I ought to not."),
	txt("I'm sure to have mountains of work upon my unexpected return."),
	txt("Peoples' campaigns, marriage proposals..."),
	txt("Would you believe it? This era's Miare doesn't see fit to give me an entry in the Gensokyo Chronicle!"),
	txt("I even wrote it for her! I personally deliver a copy every week, but I'm always turned away by the servants."),
	txt("Troublesome, surely..."),
	txt("Besides that, marriage proposals?"),
	txt("Yes, yes. None of them are even close to worthy."),
	txt("Many of them from the people that seem to give me sneers on the street, even."),
	txt("My landlord even frequents the list! He's old, and he always looks like he wants something from me."),
	txt("Ah..."),
	txt("Do you bother reading past the sender's name, sometimes?"),
	txt("Not even once."),
	txt("I would recommend trying, if only for the humor of it."),
	txt("And there may be some... feelings... that might be worth understanding, even if you cannot reciprocate."),
	txt("Hmmm? Sounds wise-ish."),
	txt("Ah, of course you'd still have it in you, Kaguya, ya old player."),
	txt("I bet you're still getting courted on the daily."),
	txt("Oh, not at all. The forest does wonders for keeping out the riff-raff, disregarding that assassin of mine."),
	txt("I don't suppose I've heard anything of the sort since-"),
	txt("No, there was one bold girl during my stay on the moon after leaving Earth."),
	txt("But she wasn't to a princess' standards."),
	txt("I wouldn't know. Once word got out, she was punished severely. I never saw her face."),
	txt("Ouch."),
	txt("The Lunar Capital is rigid in its ways."),
	txt("..."),
	txt("...Have I given you something to consider, Kotohime?"),
	txt("Yes."),
	txt("Let's get you in the game, Kaguya."),
	txt("Gensokyo isn't so uptight as the Lunar Capital."),
	txt("Why not give that romance thing another try?"),
	txt("Kotohime, are you insane?"),
	txt("It's the only way anything gets done."),
	txt("In the first place, I'm not someone who can just show myself freely. Everybody's heard of my past."),
	txt("Hm."),
	txt("Eirin wouldn't entertain the thought."),
	txt("Hmm~? Is she your superior~?"),
	txt("No... but that is the top of the list. It is infeasible."),
	txt("Perhaps... but are you opposed to the idea?"),
	txt("Is there truly no man or woman who can satisfy the isolated, cruel beauty Kaguya-hime?"),
	txt("Oh, woe is her, only to ever have been given such meek and impure love!"),
	txt("Stop it, you."),
	txt("It is true that your proposition is interesting."),
	txt("I simply cannot imagine how it could be approached."),
	txt("It can be done."),
	txt("For your first point, that you're too well-known..."),
	txt("There is a certain social circle I maintain that is fairly out-of-touch."),
	txt("...They couldn't be that ignorant."),
	txt("There are many walks of life, dear princess. They only all converge on their origin and termination."),
	txt("Oh, wait, not even that."),
	txt("But, in Gensokyo?"),
	txt("In Gensokyo."),
	txt("If there really is a place I can enter without any biases amongst its denizens..."),
	txt("Then, we just need to sneak out."),
	txt("Always thrilling. How will we do it?"),
	
	],[
	
	txt(""),
	
	])
	
	endevent = c_null;
}