function txt_elly() {
	
	msg = msglang([
	
	txt("None of these women seem terribly approachable...", KAGUYA.NORMAL, SPRITEPOS.MIDRIGHT, s_thebar, function() {music_set(mus.null)}),
	txt("Admittedly, the bachelorettes of the Twilight Bar are a fair bit eccentric.", KOTOHIME.THINKING, SPRITEPOS.RIGHT),
	txt("|c102137255Who could have guessed?"),
	txt("Slow day, is it?"),
	txt("Yield not, Ka- Tsukiko!", KOTOHIME.WINK),
	txt("Please do remember my new name."),
	txt("For there is yet still a lonely lady just around the corner!", KOTOHIME.HAPPY),
	txt("This feels somewhat ironic. Have I already reached desperation?"),
	txt("Hark; just behind that pillar lies our perfect target!", KOTOHIME.HAPPY),
	txt("Calling them a \"target\"... this really is a crass mission."),
	txt("Well what is it to you, Tsukiko!?", KOTOHIME.HAPPY),
	txt("Are you not a woman of common birth, simply shooting your shot with some locals? No shame in that.", KOTOHIME.HAPPY),
	txt("...Very well. I will continue to entertain this goal."),
	txt("|c160160160The two step away from the bar, and orbit the pillar until they can see the table behind it.", u, u, s_table),
	txt("|c160160160A woman in a deep crimson dress sits, contemplating under a pale hood."),
	txt("Good evening."),
	txt("|c160160160Startled, she unsheathes her eyes at the newcomer."),
	txt("Oh... hi.", ELLY.CONFUSED, u, u, function() {music_set(mus.bar)}),
	txt("Did you need something?", ELLY.FAKELAUGH),
	txt("Not terribly much. I had been enjoying this bar, and became curious to make the acquaintence of one of its' regulars."),
	txt("May I?"),
	txt("Um, sure.", ELLY.SURPRISED),
	txt("|c160160160Kaguya gracefully takes a seat across from the hooded woman."),
	txt("My name is Tsukiko. It's nice to meet you."),
	txt("Elly. Same here.", ELLY.FAKELAUGH),
	txt("Elly, may I ask about that weapon of yours?"),
	txt("It's very elegant."),
	txt("Thanks... it's a scythe.", ELLY.FAKELAUGH),
	txt("Do you work as a shinigami, perchance?"),
	txt("I rarely see such sort in the commonplace of Gensokyo."),
	txt("Well, not really. I'm more of a \"reaper\" than a shinigami.", ELLY.BORED),
	txt("Oh? What's a reaper?"),
	txt("It's basically the same thing as a shinigami, but we aren't really tied to a system.", ELLY.FAKELAUGH),
	txt("We just do our work where we're needed.", ELLY.FAKELAUGH),
	txt("That sounds nice. No bureaucracy."),
	txt("Kinda, but it's easy to become not-needed.", ELLY.FAKELAUGH),
	txt("It was easy a long time ago, before the era of science in the outside world.", ELLY.BORED),
	txt("But eventually, we all had to move to somewhere like here.", ELLY.ANNOYED),
	txt("Bounded little worlds that are hard to move between.", ELLY.ANNOYED),
	txt("Were you around back then?", ELLY.CONFUSED),
	txt("I was... but I've always lived in Gensokyo."),
	txt("I imagine it must feel suffocating, to go from the wide plains of the west to our quaint valley, here."),
	txt("I'm mostly over it. I just don't know what to do.", ELLY.FAKELAUGH),
	txt("Gensokyo is nice. Makai was nice, but it's a dangerous place.", ELLY.BORED),
	txt("Magic and danmaku isn't really my strong suit. I can use this scythe well, but...", ELLY.BORED),
	txt("I can sympathize. I'm capable when it comes to magical combat, but I don't have the constitution or technique for brawls."),
	txt("...Do you get into brawls much, in Gensokyo?", ELLY.CONFUSED),
	txt("Well... surprisingly, yes. I've got an enemy who leaves me little other choice."),
	txt("To be honest, I would really like to fight like that again.", ELLY.BORED),
	txt("Those religion battles seemed like the perfect time to jump in.", ELLY.BORED),
	txt("Ah, I remember those..."),
	txt("Did something have you hesitate?"),
	txt("Well, yeah. Even if I'm going easy, this weapon of mine isn't exactly friendly to most people.", ELLY.FAKELAUGH),
	txt("And I don't want to have my back pushed against a wall by someone weaker than me just because I can't use my scythe.", ELLY.FAKELAUGH),
	txt("The shrine maiden wouldn't apprciate it much either, I imagine?"),
	txt("No... so I'm out of practice and out of work.", ELLY.BORED),
	txt("That scythe of yours, I wonder..."),
	txt("Hm... never mind that."),
	txt("Anyway, uh...", ELLY.FAKELAUGH),
	txt("Tsukiko."),
	txt("Tsukiko. Sorry.", ELLY.SURPRISED),
	txt("Tsukiko, how did you find this place? Just luck?", ELLY.FAKELAUGH),
	txt("Well, actually-"),
	txt("Hiii~", KOTOHIME.HAPPY),
	txt("Kotohime. Welcome.", ELLY.SURPRISED),
	txt("Spare the greetings, my friend. I've been just out of sight this entire time.", KOTOHIME.HAPPY),
	txt("Snooping as usual, then.", ELLY.BORED),
	txt("I would call it \"observation\".", KOTOHIME.HAPPY),
	txt("|c160160160Kotohime slides into the seat next to Kaguya at the table."),
	txt("I am entrusting my dear Tsukiko to you, you see.", KOTOHIME.HAPPY),
	txt("Now I want to know how you two even met, but I know asking is pointless.", ELLY.BORED),
	txt("I have no qualms with sharing."),
	txt("|c102137255Although I'll have to edit around \"Kaguya\"..."),
	txt("My manor is in a quite remote location."),
	txt("Manor? You're nobility?", ELLY.SURPRISED),
	txt("Oh, no. It's just something me and my friends happened upon. A lucky place to have taken residence at."),
	txt("However, it's very hard to find."),
	txt("I was impressed when a lone human woman found it."),
	txt("That's me!", KOTOHIME.HAPPY),
	txt("She threw herself in with us, seemingly just looking for a good time."),
	txt("Uh-huh.", ELLY.FAKELAUGH),
	txt("My friends are rather work-oriented, and were quick to drive her out."),
	txt("Magicians, or something?", ELLY.SURPRISED),
	txt("Of the sort."),
	txt("But I turned around and offered my services as a noblewoman of endless talents!", KOTOHIME.HAPPY),
	txt("...So, she came to our employment in retreiving some rare items we had sent out for."),
	txt("Hmmmm~", ELLY.BORED),
	txt("That's pretty hard to believe.", ELLY.BORED),
	txt("Kotohime hasn't exactly...", ELLY.FAKELAUGH),
	txt("Oh, but I have.", KOTOHIME.HAPPY),
	txt("...Now you do?", ELLY.SURPRISED),
	txt("Now I do.", KOTOHIME.HAPPY),
	txt("I guess I shouldn't pry. Cool story.", ELLY.FAKELAUGH),
	txt("It's been nice talking to you, Tsukiko. Will you stop by the bar again?", ELLY.HAPPY),
	txt("Oh. I hadn't thought that far ahead."),
	txt("|c102137255I truly hadn't."),
	txt("|c102137255Can I keep this up?"),
	txt("Hey, why not?", KOTOHIME.HAPPY),
	txt("Next time you can meet Rika, too.", KOTOHIME.HAPPY),
	txt("Yes, I..."),
	txt("|c102137255Ah... to do this again?"),
	txt("|c102137255With \"Tsukiko\"..."),
	txt("|c102137255No, this is wrong."),
	txt("|c102137255This sort of deception... this friviolity... it is disrespectful."),
	txt("...No. Apologies.", u, u, s_bar, function() {music_set(mus.null)}),
	txt("Truthfully, I must be going now."),
	txt("...Oh. That's a shame.", ELLY.CONFUSED),
	txt("Elly. Kotohime. It was pleasant."),
	txt("Wait, wh-", KOTOHIME.HAPPY),
	txt("|c160160160Kaguya turns away from the two, and walks out of the bar."),
	
	],[
	
	txt(""),
	
	])
	
	endevent = function() {textbox_create(txt_leaving)};
}