function txt_kagumoku() {

	global.thecolor = 0xFFFFFF;
	c_additem(ITEMS.HIDE);
	msg = msglang([
	
	
	txt("Time goes by fast, doesn't it?", u, u, s_stars, function() {music_set(mus.intermission)}),
	txt("At least, for some of us. We think we have all of eternity ahead of us, and that conviction results in lethargy."),
	txt("And by the time one realizes how much time they've wasted, it's too late."),
	txt("But if they realize it early, their life becomes dominated by the fear of death."),
	txt("Is that really a way to live?"),
	ptxt(),
	txt("This is a very biased view, of course. Only a regular human would think something like this."),
	txt("Kana Anaberal may die from an accident or a particularly nasty spell, but she does not age."),
	txt("And the Hourai Immortals-- Fujiwara no Mokou and Houraisan Kaguya-- really do have an eternity ahead of them."),
	txt("To be honest... I can't tell if I envy or pity them."),
	ptxt(),
	
	txt("Before I knew it, years had passed.", u, u, s_crescent),
	txt("The House of Eternity's spell had been revoked, due to a series of encounters that convinced Kaguya to move forward."),
	txt("Its residents would leave the Bamboo Forest quite often, interacting with the humans and youkai on a regular basis."),
	txt("They even frequently carried out services for the residents of the Human Village."),
	txt("Kana adjusted well to life there, to the point she rarely ever left."),
	txt("I visited them far more often, much to the behest of my parents."),
	ptxt(),
	txt("Though, one thing had stayed mostly the same..."),
	
	//ntxt(0, u, u, u, function() {audio_play_sound(snd_bomb, 0, false)}),
	
	//boom punchy impact frame and big BOOM fire sound effect
	
	ntxt(0, u, u, u, function() {music_set(mus.undertale)}),
	
	txt("KAGUYAAAAA!", MOKOU.DEF, u, s_bambooday2, function() {textbox_set_type(global.textzpix)}),
	txt("COME BACK HERE, YOU COWARD!", MOKOU.DEF),
	
	ptxt(),
	txt("A scream from above the trees rang in my ears.", u, u, s_bambooday, function() {textbox_set_type(global.textnvl)}),
	txt("Two figures flew suspended high in the air, exchanging verbal blows."),
	txt("Kaguya and Mokou had been flinging their heaviest attacks at each other, but for some reason Kaguya had flown far out of Mokou's reach."),
	txt("It was almost surreal seeing the rain of fire and magic energy stop for even a few seconds."),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.RIGHT),
	ntxt(0, REISEN.DEF, SPRITEPOS.CENTER),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.LEFT),
	txt("Kana, Reisen, and I stood on the ground, watching the spectacle in the sky."),
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	
	txt("Oh Mokou, I can't truly participate yet. Your attacks weren't *exciting* enough.", KAGUYA.FUFUFU, SPRITEPOS.LEFT, s_bambooday2, function() {textbox_set_type(global.textzpix)}),
	txt("What the hell are you talking about!?", MOKOU.HMPH, SPRITEPOS.RIGHT),
	txt("I've kicked you so hard your whole body went flying through three dozen trees, and thrown seventy-two fireballs at you!", MOKOU.MAD),
	txt("Oh yes, those were very violent and painful. But I haven't been seeing the fun yet~~!", KAGUYA.FUFUFU),
	txt("You insufferable piece of...", MOKOU.HMPH),
	txt("The *fun* is in burning YOUR smug little face off!", MOKOU.REALLYMAD),
	txt("And?", KAGUYA.YAY),
	txt("Then skewering you with a stray bamboo shoot and ripping off your limbs one by one!", MOKOU.REALLYMAD),
	txt("And?", KAGUYA.YAY),
	txt("Then clawing out your esophagus and forcefeeding it to you,", MOKOU.REALLYMAD),
	txt("Chopping your skull clean in two,", MOKOU.REALLYMAD),
	txt("And rearranging your body until your teeth are in your hands and your brains are in your lungs,", MOKOU.REALLYMAD),
	txt("While we're falling into a pit of lava on the blazing surface of Venus!", MOKOU.REALLYMAD),
	txt("Ah-ha, that's more like it! I'm really feeling the fire now!", KAGUYA.COCKY),
	txt("Come to me, archenemy!", KAGUYA.COCKY),
	txt("Gladly!", MOKOU.COCKY),
	
	ntxt(0, KAGUYA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, MOKOU.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(21, u, u, u, function() {audio_play_sound(snd_attack1, 0, false)}),
	ntxt(11, u, u, u, function() {audio_play_sound(snd_attack2, 0, false)}),
	ntxt(09, u, u, u, function() {audio_play_sound(snd_attack1, 0, false)}),
	ntxt(32, u, u, u, function() {audio_play_sound(snd_game_explosion9, 0, false)}),
	ntxt(11, u, u, u, function() {audio_play_sound(snd_attack1, 0, false)}),
	ntxt(11, u, u, u, function() {audio_play_sound(snd_attack1, 0, false)}),
	ntxt(31, u, u, u, function() {audio_play_sound(snd_attack2, 0, false)}),
	ntxt(21, u, u, u, function() {audio_play_sound(snd_attack1, 0, false)}),
	ntxt(26, u, u, u, function() {audio_play_sound(snd_attack2, 0, false)}),
	ntxt(42, u, u, u, function() {audio_play_sound(snd_game_explosion9, 0, false)}),
	//BOOM BAM PAWOOSHY
	//PICHUUN SHSHK KUWAAABAM
	//BUREHM PSSSSHHHHHHH-BRUH
	
	txt("How does that make you feel!?", MOKOU.COCKY, SPRITEPOS.CENTER),
	//haha baka writing
	//i dont feel like swearing so uguu beans
	txt("Splendid, thank you!", KAGUYA.YAY, SPRITEPOS.RIGHT),
	txt("I see that you favor more focused, high-power attacks over large blasts.", KAGUYA.DEF),
	txt("It's an admirable effort, but you can't expect to hit me with-- |w0030 |- ", KAGUYA.FUFUFU),
	//BOOM PWAPASH PIQUIUUUM
	//pichuun and resurect sound
	ntxt(0, KAGUYA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, MOKOU.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(20, u, u, u, function() {audio_play_sound(snd_shoot1, 0, false)}),
	ntxt(90, u, u, u, function() {audio_play_sound(snd_full_laser, 0, false)}),
	ntxt(59, u, u, u, function() {audio_play_sound(snd_game_explosion3, 0, false)}),
	ntxt(40, u, u, u, function() {audio_play_sound(snd_game_explosion4, 0, false)}),
	
	txt("Stop talking and kill me already!", MOKOU.COCKY, SPRITEPOS.LEFT),
	txt("...", KAGUYA.MAD, SPRITEPOS.MIDRIGHT),
	txt("Gladly.", KAGUYA.MAD),
	ntxt(0, KAGUYA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, MOKOU.NEUTRAL, SPRITEPOS.HIDDEN),
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.RIGHT, s_bambooday),
	ntxt(0, REISEN.DEF, SPRITEPOS.CENTER),
	ntxt(0, ME.YAY, SPRITEPOS.LEFT),
	
	txt("This is so fun!", ME.YAY),
	txt("I wish I could see this more often!", ME.YAY),
	txt("Hey Reisen, what are they gonna do next?", ME.YAY),	
	txt("My guess is they'll start fighting close-quarters and crashland into the ground somewhere.", REISEN.DEF),
	txt("So let's just... make sure we're out of their way when that happens.", REISEN.UGGH),
	txt("Where do you think they're gonna land?", KANA.BRUH),
	txt("Oh, probably a couple meters to our left.", REISEN.DEF),
		
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN, s_bambooday2),
	
	
	ntxt(36, u, u, u, function() {audio_play_sound(snd_punch2c, 0, false)}),
	ntxt(36, u, u, u, function() {audio_play_sound(snd_middle_kick, 0, false)}),
	ntxt(17, u, u, u, function() {audio_play_sound(snd_jab, 0, false)}),
	ntxt(16, u, u, u, function() {audio_play_sound(snd_punch2c, 0, false)}),
	ntxt(48, u, u, u, function() {audio_play_sound(snd_straight_punch, 0, false)}),
	ntxt(50, u, u, u, function() {audio_play_sound(snd_game_explosion3, 0, false)}),
	ntxt(42, u, u, u, function() {audio_play_sound(snd_game_explosion4, 0, false)}),
	
	txt("Hey, you're getting better at this whole punching thing!", MOKOU.COCKY, SPRITEPOS.CENTER),
	txt("You almost made me flinch.", MOKOU.SMUG),
	txt("I'll take that as the highest possible compliment.", KAGUYA.FUFUFU, SPRITEPOS.RIGHT),
	ntxt(0, KAGUYA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, MOKOU.NEUTRAL, SPRITEPOS.HIDDEN),
	
	///boom
	//PUNCHYPUNCH WAPOOSH
	//KIK KIIK
	//WHEEEEEEOOOW
	//BWOOOJGODAOJD
	
	
	ntxt(30, u, u, u, function() {audio_play_sound(snd_jab, 0, false)}),
	ntxt(20, u, u, u, function() {audio_play_sound(snd_middle_kick, 0, false)}),
	ntxt(12, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(11, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(14, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(08, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(19, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(04, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(06, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(06, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(06, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(03, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(03, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(03, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(02, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(02, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(02, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(05, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(04, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(04, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(07, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(07, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(07, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(07, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(01, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(13, u, u, u, function() {audio_play_sound(snd_middle_punch1, 0, false)}),
	ntxt(150, u, u, u, function() {audio_play_sound(snd_falling2a, 0, false)}),
	ntxt(30, u, u, u, function() {audio_play_sound(snd_explosion2, 0, false)}),
	
	txt("...|w0150 |- ", u, u , s_crater),
	ntxt(0, ME.WHAA, SPRITEPOS.LEFT),
	ntxt(0, REISEN.UGGH, SPRITEPOS.CENTER),
	ntxt(0070, KANA.SCARED, SPRITEPOS.RIGHT, s_bambooday),
	txt("Are you absolutely sure we should be here!?", KANA.SCARED),
	txt("...No.", REISEN.UGGH),
	txt("I'm only risking my life here to make sure they don't do anything stupid.", REISEN.UGGH),
	txt("Like when they burned down half the forest?", KANA.BRUH),
	txt("Worse.", REISEN.UGGH),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	
	
	ntxt(0, u, u, u, function() {audio_play_sound(snd_hard_attack, 0, false)}),
	txt("You absolutely--|w0030 |- ", KAGUYA.MAD, SPRITEPOS.RIGHT, s_crater, function() {audio_play_sound(snd_straight_punch, 0, false)}),
	ntxt(0, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	txt("Smug little--|w0030 |- ", MOKOU.MAD, SPRITEPOS.MIDLEFT, u, function() {audio_play_sound(snd_kick2, 0, false)}),
	ntxt(0, MOKOU.DEF, SPRITEPOS.HIDDEN),
	txt("Brutish--|w0030 |- ", KAGUYA.MAD, SPRITEPOS.RIGHT, u, function() {audio_play_sound(snd_punch2c, 0, false)}),
	ntxt(0, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	txt("Cowardly--|w0030 |- ", MOKOU.MAD, SPRITEPOS.MIDLEFT, u, function() {audio_play_sound(snd_heavy_punch3, 0, false)}),
	ntxt(0108, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, KAGUYA.MADEARTH, SPRITEPOS.RIGHT),
	ntxt(300, MOKOU.MADMOON, SPRITEPOS.MIDLEFT),
	//BOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOM
	ntxt(0, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(57, MOKOU.DEF, SPRITEPOS.HIDDEN),
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.RIGHT, s_bambooday),
	ntxt(0, REISEN.DEF, SPRITEPOS.CENTER),
	ntxt(40, ME.POG, SPRITEPOS.LEFT),
	
	txt("...", KANA.SCARED),
	txt("I think we should go.", KANA.SCARED),
	txt("Yeah. They won't get tired for a while.", REISEN.DEF),
	txt("And *we* still have fifty-six boxes of medicine to deliver by sundown.", REISEN.UGGH),
	//fade out
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	
	ntxt(0150, u, u, s_crescent2, function() {music_set(mus.eientei)}),
	txt("And my Rook takes your Gold General...", REISEN.YAY, SPRITEPOS.RIGHT, s_eienteihall2),
	txt("How the--", KANA.SCARED, SPRITEPOS.CENTER),
	txt("Oh, I see.", KANA.AWW),
	txt("Wow, is she actually gonna beat you this time?", ME.YAY, SPRITEPOS.LEFT),
	txt("She is absolutely not.", KANA.MAD),
	txt("Because I have both of her queens!", KANA.COCKY),
	txt("How do ya like THIS!?", KANA.COCKY),
	txt("...", REISEN.WOAH),
	ptxt(),
	txt("After all our work was done, the three of us took turns playing Chesshogi.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("It was great fun like always, but something laid on my mind heavily that night."),
	txt("I had suspected it for years now, but what I saw that day pushed it to the forefront."),
	
	txt("Hey... why do Kaguya and Mokou fight like that?", ME.DEF, u, u, function() {textbox_set_type(global.textzpix)}),
	txt("Beats me.", REISEN.DEF),
	txt("They've been doing it for 300 years, or so I've heard. Mokou's still pissed at Kaguya from something back in the 9th century.", REISEN.DEF),
	txt("But it's not like those fights actually accomplish anything.", REISEN.UGGH),
	txt("My best guess is that immortality has turned them into masochists.", REISEN.DEF),
	txt("...", ME.HEHE),
	txt("I think they secretly like each other.", ME.DEF),
	txt("...Huh?", KANA.BRUH),
	txt("What kinda nonsense is that?", REISEN.UGGH),
	txt("I'm serious, you two!", ME.POGQMARK),
	txt("There's just something with them.", ME.HEHE),
	txt("Something *between* them.", ME.HEHE),
	txt("I think your romance sensors need some tuning.", KANA.BRUH),
	txt("Please, just trust me on this one!", ME.POG),
	txt("If we just set them up together, with the right situations, they might just become a couple!", ME.WINKYHEART),
	txt("You are out of your mind.", REISEN.UGGH),
	txt("Just because it worked for Kana and I doesn't mean it will work for people who murder each other weekly.", REISEN.DEF),
	txt("Sure, it'd be nice if they did something else for a change, but there's no way that could happen in any of our lifetimes.", REISEN.DEF),	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	///door slide sound effect
	txt("HEY EVERYONE, I'M HOOOOME!!!", KAGUYA.YAY, SPRITEPOS.CENTER, s_eienteihall1),
	ntxt(0, KAGUYA.YAY, SPRITEPOS.HIDDEN),	
	ntxt(0, ME.POG, SPRITEPOS.LEFT),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.CENTER),
	txt("Jeez, does she have to be so loud?", REISEN.UGGH, SPRITEPOS.RIGHT, s_eienteihall2),
	txt("Sorry, I must've rubbed off on her.", ME.DEF),
	txt("You don't look sorry.", REISEN.UGGH),
	txt("I don't.", ME.SMUG),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	txt("Welcome back, Princess. How was your afternoon stroll?", REISEN.DEF),
	txt("...", KAGUYA.AWW, SPRITEPOS.LEFT),
	txt("To be frank... sub-par.", KAGUYA.AWW),
	txt("Mokou and I threw practically the same insults and the same attacks as our last fight.", KAGUYA.AWW),
	txt("I believed it'd take at least two more millennia for our death battles to become boring...", KAGUYA.NEUTRAL),
	txt("But it seems our spark has been fading in recent months.", KAGUYA.AWW),
	txt("I just wish we did something else for a change.", KAGUYA.WAAH),
	txt("???", REISEN.WOAH),
	txt("No matter.", KAGUYA.NEUTRAL),
	txt("Dying hundreds of times has tired me greatly.", KAGUYA.DEF),
	txt("I must snooze.", KAGUYA.DEF),
	
	ntxt(41, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	
	txt("See?", ME.SMUG, SPRITEPOS.MIDLEFT),
	txt("...You may have a point.", REISEN.HEH),
	txt("Not with them liking each other--!!", REISEN.MAD),
	txt("But the sooner they stop those destructive battles, the better.", REISEN.HEH),
	txt("Yay!", ME.YAY),
	txt("What should we do about it, then?", KANA.DEF, SPRITEPOS.MIDRIGHT),
	txt("They likely wouldn't be on board with anything clearly friendly, so we should set up something competitive.", REISEN.DEF),
	txt("...I have an idea.", ME.HEHE),
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	
	txt("Only a fortnight ago, I had stumbled across a strange device in Muenzuka. It didn't function, but I wished to discover its secrets.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("Kourindou was no help, so I brought it to Eirin to figure out what it did. In only twenty minutes, she had disassembled the device, put it back together, and written a comprehensive manual on its use."),
	txt("It was called a peecee nintey ate.", u, u, s_peecee),
	//beary funni but kinda doomb
	//keep it or now
	txt("It had many stated purposes, but the one that stuck out in my mind was..."),
	txt("Playing games."),
	
	ptxt(),
	txt("To put a long story short, I made it my conviction to use this to help Kaguya and Mokou."),
	txt("That... and my own curiosity."),
	txt("With a little bit of help from Eirin, Kana and I learned as much about the systems as we could... as well as a strange task called \"programming.\""),
	
	ptxt(),
	txt("...|w0222 |- ", u, u, s_eienteihall3, function() {music_set(mus.keyboard)}),
	
	txt("Ooh, let's see... what about chain reactions?", KANA.YAY, SPRITEPOS.CENTER, u, function() {textbox_set_type(global.textzpix)}),
	txt("If one enemy explodes close to another, they all explode one by one and kill each other!", KANA.COCKY),
	txt("That's the coolest thing I've ever heard!", ME.YAY, SPRITEPOS.RIGHT),
	txt("Putting that in right now!", ME.WINKY),	
	txt("And the more chain reactions, the more meteorites fall, and the more meteorites fall, the more bullets on the screen!", KANA.DEF),
	txt("That would be complete chaos.", ME.NEUTRAL),
	txt("Let's do it!", ME.YAY),
	
	txt("Hey, Kana.", REISEN.YAY, SPRITEPOS.LEFT),
	txt("You ready for bed?", REISEN.YAY),
	txt("Ah... sorry. I'm helping her out right now.", KANA.AWW),
	txt("...With what?", REISEN.DEF),
	txt("Making a game. It's one of the things these peecees can do.", KANA.NEUTRAL),
	txt("It's a lot of work, and we want to get it done by tomorrow so Kaguya and Mokou play it.", KANA.NEUTRAL),
	txt("Because *someone* invited Mokou over tomorrow without having anything ready.", KANA.MAD),
	txt("Hey, hey, it's alright!", ME.YAY),
	txt("This way they can go kissy-kiss even sooner!", ME.YAY),
	txt("Sounds terrifying. Can I help at all?", REISEN.DEF),
	txt("Not really.", KANA.NEUTRAL),
	txt("It's a two-person job. I read the manual out loud and give her ideas, and she uses that clickety-thing.", KANA.DEF),
	txt("Huh. Then I'll leave you to it. Just make sure you don't super-die from exhaustion.", REISEN.DEF),
	txt("We won't. Probably.", KANA.NEUTRAL),
	txt("G'night, luv.", REISEN.YAY),
	txt("Goodnight, sugarbunny.", KANA.YAY),
	//i do not know how to convey that kana and raisin are lovers
	//aaaaaaaaaaaaaaaaaaaaaaaa
	ntxt(0, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("... |w0164 |- ", u, u, u, function() {textbox_set_type(global.textnvl)}),
	
	txt("Ooh, what about enemy attacks?", KANA.YAY, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("What are those?", ME.YAY, SPRITEPOS.MIDLEFT),
	txt("You can fill up your gauge to throw a clone of yourself at the other player!", KANA.DEF),
	txt("And the clone does a bunch of attacks that are even harder to dodge than your normal gauge attacks!", KANA.COCKY),
	txt("But there can only be one clone at a time, so if you're being attacked by a clone, you can make a clone to make the enemy's clone go away!", KANA.DEF),
	txt("You're a genius, Kana.", ME.SMUG),
	txt("Oh, don't flatter me like that!", KANA.YAY),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("... |w0222 |- ", u, u, u, function() {textbox_set_type(global.textnvl)}),
	
	txt("This is just like old times, isn't?", KANA.YAY, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("What do you mean?", ME.DEF, SPRITEPOS.MIDLEFT),
	txt("We haven't been together like this in years.", KANA.WINKY),
	txt("Just us two.", KANA.YAY),
	txt("We haven't.", ME.NEUTRAL),
	txt("...", KANA.NEUTRAL),
	txt("...", KANA.DISTANT),
	txt("Are you okay?", ME.NEUTRAL),
	txt("Yeah, yeah.", KANA.DEF),
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.HIDDEN),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.HIDDEN),
	
	//probably put more stuff in here so kana aint HEY BWOAH DRAMA
	ptxt(),
	txt("... |w0202 |- ", u, u, u, function() {textbox_set_type(global.textnvl)}),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.MIDLEFT),
	
	txt("...I've been thinking lately. About how we got here.", KANA.DISTANT, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("Ever since that morning we watched the sunrise.", KANA.DISTANT),	
	txt("It's strange, you know? How much feelings like that can change.", KANA.DEF),
	txt("At first, Reisen was my second choice. Even after I confessed, our love felt... lesser. And every time I looked into her eyes, that was all I could think about.", KANA.AWW),
	txt("I overcame it a while ago. We're happy together now, and I wouldn't have it any other way.", KANA.DEF),
	txt("But...", KANA.AWW),
	txt("...", ME.DISTANT),
	txt("Sorry, we shouldn't be talking about this. It's in the past now.", KANA.DISTANT),
	txt("I'm the one who should be sorry.", ME.DISAPOINT, u, u, function() {music_set(mus.null)}),
	txt("For what I said back at the Misty Lake. However I should've responded, that wasn't it.", ME.DISAPOINT),
	txt("I just made you sad for no reason.", ME.DISAPOINT),
	
	txt("...", KANA.NEUTRAL),
	txt("Did you love me back then?", KANA.NEUTRAL),
	txt("Did you have *any* desire to be with me like that?", KANA.NEUTRAL),
	txt("...No.", ME.DISTANT),
	txt("But...|w0050 maybe I should've said yes.", ME.DISTANT),
	txt("I just wanted to make you happy, you know?", ME.DISAPOINT),
	txt("If we were together, then even if I saw you as a friend...", ME.DISAPOINT),
	txt("You'd have your dream girl.", ME.DISTANT),
	
	txt("...", KANA.DISTANT),
	txt("I wouldn't want you to lie to me. Not like you do with everyone else.", KANA.DISTANT),
	txt("You've made me happy just by being you.", KANA.YAY),
	//txt("Looking back, I think it was just that you were in the right place at the right time.", KANA.AWW),
	txt("And even if I was sad at first... it's okay how things went back then. Like I said, I wouldn't have it any other way.", KANA.DEF),
	
	txt("...", ME.DISTANT),
	txt("Thank you.", ME.TINYSMIRK),
	txt("You're welcome.", KANA.YAY),
	txt("Let's get this game done, okay?", KANA.WINKY),
	txt("Let's.", ME.YAY),
	ntxt(0, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, ME.DEF, SPRITEPOS.HIDDEN, u, function() {music_set(mus.keyboard)}),
	
	ptxt(),
	txt("...|w0333 |- ", u, u, s_crescent2, function() {textbox_set_type(global.textnvl)}),
	ntxt(0, u, u, u, function() {music_set(mus.eientei)}),
	
	txt("So what am I here for, exactly?", MOKOU.NEUTRAL, SPRITEPOS.CENTER, s_eienteihall1, function() {textbox_set_type(global.textzpix)}),
	txt("Fun and games for the whole family!", ME.YAY, SPRITEPOS.RIGHT),
	txt("Heh. Alright.", MOKOU.DEF),
	txt("By \"the whole family\" do you mean Kaguya and I?", MOKOU.DEF),
	txt("Yes!", ME.WINKY),
	txt("Okay...", MOKOU.HMPH),
	txt("And what do I get by subjecting myself to this?", MOKOU.HMPH),
	txt("You get the games themselves!", ME.YAY),
	txt("Why would I care about some toy?", MOKOU.BRUH),
	txt("Because...", ME.HEHE),
	ntxt(0, MOKOU.DEF, SPRITEPOS.HIDDEN),
	txt("THIS is our game!", ME.WINKY, SPRITEPOS.HIDDEN, s_peeceescreen),
	ntxt(0050),
	//click, power on
	
	ntxt(0123, u, u, s_kselect),
	ntxt(0080, u, u, s_kdemo),
	
	txt("Amazing, isn't it?", ME.HEHE),	
	txt("Oh my gosh, this...", MOKOU.NEUTRAL, SPRITEPOS.MIDLEFT, s_eienteihall1),
	txt("This is like that brick I have!", MOKOU.YAY),
	txt("...Brick?", ME.NEUTRAL, SPRITEPOS.RIGHT),
	txt("Yeah, the brick. I got it from this kid from the Outside World who found his way into the forest.", MOKOU.DEF),
	txt("Funny one, he was. I could barely understand half his vocabulary.", MOKOU.NEUTRAL),
	txt("I escorted him out, and he gave me this little grey brick as thanks.", MOKOU.YAY),
	txt("He said something like... \"This gizmo's got some giga-epic retro games! It's totally fire!\"", MOKOU.DEF),
	txt("It had this little screen with a bunch of characters on it, like a puppet show. But the crazy thing was, I could control the characters!", MOKOU.YAY),
	txt("That thing gave me hours of fun for the whole day afterwards.", MOKOU.DEF),	
	txt("And then outta nowhere, it stopped working. The characters wouldn't appear anymore.", MOKOU.SADSMILE),
	txt("Now I just use it as a paperweight.", MOKOU.SADSMILE),	
	txt("Wow, that's amazing!", ME.POG),
	txt("Sounds like the batteries ran out.", ME.HEHE),
	txt("Batteries are a rarity over here, but we can just use a couple spells to keep it running forever!", ME.YAY),
	txt("Really?", MOKOU.YAY),
	txt("Yeah! Tomorrow we'll get you one, alright?", ME.YAY),
	txt("But *only* if you do your best in this challenge.", ME.SMUG),
	txt("...", MOKOU.NEUTRAL),
	txt("Deal.", MOKOU.DEF),
	
	/*
	txt("Yay!", ME.YAY),
	txt("Kaguya isn't here, is she?", MOKOU.BRUH),
	txt("Nope! She's been taking a nap for seven hours.", ME.DEF),
	txt("Well, since I'm the first one here,", MOKOU.DEF),
	txt("How about I get in a liiiiiitle practice?", MOKOU.SMUG),
	txt("Go ahead!", ME.YAY),
	txt("Mokou surprised me with how willing she was. It seemed this game had intrigued her.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("She was... quite terrible at it. But that was to be expected of someone who hadn't played a game before."),
	txt("And as the hours went by, she rapidly improved. By the end, she knew the ins and outs of the game."),
	txt("I made the thing, and she had become better than me."),
	*/
	
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	ptxt(),	
	txt("Hours of work and setup later, we had finally arrived at the event's time.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("Kaguya showed up very late, so she wasn't kept waiting for even a second."),
	txt("Kana and Reisen were off doing errands, so it was only me and the contestants."),
	txt("I quickly explained a little bit about the game to Kaguya and Mokou, for the sake of expedience."),
	
	ntxt(0, u, u, u, function() {music_set(mus.glossary)}),
	txt("Ladies and ladies, welcome to the first ever CLASH OF THE MOON AND THE SUN!!", ME.YAY, SPRITEPOS.CENTER, s_eienteihall2, function() {textbox_set_type(global.textzpix)}),
	txt("An event where we make your undying wishes come true!", ME.WINKY),
	ntxt(033, u, u, u, function() {audio_play_sound(snd_clapping_alone1, 0, false)}),
	txt("We have gathered our two fine contestants here today for the greatest competition in the whole House of Eternity!", ME.DEF),
	ntxt(00, KAGUYA.YAY, SPRITEPOS.RIGHT),
	txt("Houraisan Kaguya,", ME.DEF),
	ntxt(00, MOKOU.DEF, SPRITEPOS.LEFT),
	txt("And Fujiwara no Mokou!", ME.DEF),
	txt("These two lovely ladies will be competing in a brand-new sport called...", ME.HEHE),
	txt("Podding!", ME.DEF),
	txt("...What is that?", KAGUYA.NEUTRAL),
	ntxt(0, MOKOU.SMUG, SPRITEPOS.LEFT),
	txt("Podding is a new-fangled Electronic Sport!", ME.YAY),
	txt("To put it simply, you must press buttons to control a character. As for what you do...", ME.YAY),
	txt("Just approach it like danmaku!", ME.WINKYHEART),	
	txt("That sounds so very intriguing. Let's do it!", KAGUYA.FUFUFU),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	ptxt(),	
	txt("Good! Here is your arena.", ME.DEF, u, s_peeceescreen, function() {textbox_set_type(global.textnvl)}),
	txt("It's a new type of interface known as the \"Video Game!\"", ME.DEF),
	txt("Each of you must compete to see who can survive the longest in a simulated danmaku battle.", ME.DEF),
	txt("Also, due to completely unavoidable hardware limitations, the two of you must share the same keyboard to play.", ME.YAY, SPRITEPOS.RIGHT, s_eienteihall2, function() {textbox_set_type(global.textzpix)}),
	txt("I hope you don't mind that.", ME.SMUG),
	txt("Whatever works.", MOKOU.DEF, SPRITEPOS.CENTER),
	txt("Fufufu.", KAGUYA.FUFUFU, SPRITEPOS.LEFT),
	txt("That's quite quaint. Questionable, even. Quirkily quizzical, and mayhaps somewhat queer.", KAGUYA.FUFUFU),
	
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	txt("..."),	
	txt("What a strange device...", KAGUYA.NEUTRAL, SPRITEPOS.MIDRIGHT),
	txt("And... my, this seating is awfully cramped.", KAGUYA.NEUTRAL),
	txt("Y-yeah, it is...", MOKOU.NEUTRAL, SPRITEPOS.CENTER),
	txt("Are you okay, Mokou? You're looking pale.", KAGUYA.DEF),	
	txt("No, I'm... totally fine. We've been positioned like this a million times.", MOKOU.HMPH),
	txt("Ah, you're correct. But this time, we're not killing each other.", KAGUYA.YAY),
	txt("It's been a while since we've sat so close together, hasn't it? At least two-hundred years.", KAGUYA.DEF),
	txt("Yes...", MOKOU.NEUTRAL),	
	txt("Oh my, you're going awfully quiet. This is just like those times you saw me naked!", KAGUYA.FUFUFU),
	txt("Wha--", MOKOU.SURPRISED),
	txt("That has never happened!", MOKOU.HMPH),
	txt("Really? It happened just last month.", KAGUYA.DEF),
	txt("While I was trying to *kill you!* I just happened to burn off all your clothes by accident!", MOKOU.MAD),
	txt("That didn't make your cheeks any less red!", KAGUYA.WINKY),
	txt("I was on fire too!", MOKOU.REALLYMAD),
	
	txt("Are you ready!?", ME.DEF, SPRITEPOS.LEFT),
	txt("Absolutely!", KAGUYA.YAY),
	txt("Ready as I'll ever be...", MOKOU.NEUTRAL),

	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN, s_peeceescreen),
	
	ntxt(0090, u, u, s_kstart),
	txt("ROUND 1, START!", ME.DEF, u, u, function() {music_set(mus.vidya2)}),
	ntxt(0069, u, u, s_k01),
	
	txt("Ah, this truly is like our fights.", KAGUYA.DEF, u, s_k01),
	txt("It is?", MOKOU.DEF),
	txt("Yes! We charge up our attacks, and...", KAGUYA.DEF),
	ptxt(),
	ntxt(0050, u, u, s_k02),
	//play BWOOM sound effect
	ntxt(0040, u, u, s_k04),
	ntxt(0054, u, u, s_k05),
	
	txt("Send bullets at each other!", KAGUYA.DEF),
	txt("Guess so...", MOKOU.DEF, u, s_k06),
	txt("Well then, how about this!?", MOKOU.DEF, u, s_k07),
	txt("Ah, what is this? A \"boss attack\"?", KAGUYA.DEF, u, s_k09),
	txt("What is this girl doing here!?", KAGUYA.DEF),
	txt("Oh, I've been hit!", KAGUYA.DEF, s_k10),
	txt("Time for another attack!", MOKOU.DEF, s_k13),
	txt("And another!", MOKOU.DEF, s_k14),
	txt("Oh, bother. I can dodge this in real life, but not with these silly buttons!", KAGUYA.DEF, u, s_k15),
	txt("Good!", MOKOU.DEF, u, s_k16),
	txt("I've been smitten again!", KAGUYA.DEF, u, s_k17),
		
	txt("How are you moving so excellently?", KAGUYA.AWW, SPRITEPOS.MIDRIGHT, s_eienteihall2),
	txt("Skill.", MOKOU.DEF, SPRITEPOS.CENTER),
	txt("I see that. But you haven't played this game before today.", KAGUYA.NEUTRAL),
	txt("True. But while you were taking your seven-hour nap, I got in a *smidgen* of practice.", MOKOU.SMUG),
	txt("Pardon!?", KAGUYA.SHOCKED),
	txt("Yep! Mokou was playing nonstop for hours!", ME.YAY, SPRITEPOS.LEFT),
	txt("She surprised me with her willingness to play. At first she was awful, but each match showed rapid improvement.", ME.DEF),
	txt("At this point, she's better than me!", ME.WINKY),
	txt("You cheating little...", KAGUYA.MAD),
	txt("Hey, I was just punctual.", MOKOU.SMUG),
	
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	txt("Oh crap!", MOKOU.SURPRISED, u, s_k18),
	//boom explode
	txt("I wasn't looking!", MOKOU.SURPRISED, s_k20),
	//MOKOU LOSES
	
	txt("Fufufu. As to be expected of a foolish earthling.", KAGUYA.FUFUFU, u, s_k21),
	txt("Hey, don't act like you were on top the whole time! I would've won if you didn't distract me!", MOKOU.MAD),
	
	txt("ROUND TWO, START!", ME.DEF),
	ntxt(0060, u, u, s_k22),
	ntxt(0030, u, u, s_k23),
	ntxt(0080, u, u, s_k24),
	ntxt(0040, u, u, s_k25),
	ntxt(0050, u, u, s_k26),
	ntxt(0020, u, u, s_k26),
	
	txt("I can't believe it...", KAGUYA.WAAH, SPRITEPOS.MIDRIGHT, s_eienteihall2),
	txt("I can.", MOKOU.SMUG, SPRITEPOS.CENTER),	
	txt("That's it! There's no way I'll lose this round!", KAGUYA.MAD),
	txt("FINAL ROUND, START!", ME.WINKYHEART, SPRITEPOS.LEFT),
	
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	ntxt(0034, u, u, s_k28),
	ntxt(0064, u, u, s_k29),
	ntxt(0044, u, u, s_k30),
	ntxt(0024, u, u, s_k31),
	ntxt(0074, u, u, s_k32),
	ntxt(0045, u, u, s_k33),
	
	txt("What the...", MOKOU.DEF, u, s_k34),
	txt("I can't move!", MOKOU.DEF),
	txt("Silly little Mokou...", KAGUYA.FUFUFU),
	txt("I said I wouldn't lose, didn't I?", KAGUYA.DEF),	
	txt("I manipulated the eternity of your buttons.", KAGUYA.WINKY, u, s_k35),
	txt("Now you can no longer move your character.", KAGUYA.SMUG),
	txt("What the hell are you talking about!?", MOKOU.MAD, u, s_k36),
	txt("I'm gonna lose here!", MOKOU.REALLYMAD),
	txt("And I'm going to win!", KAGUYA.YAY, u, s_k37),
	txt("You slimy, cheating...", MOKOU.MAD, u, s_k38),
	
	ntxt(0069, u, u, s_k40),
	ntxt(0089, u, u, s_k41),
	
	txt("And it looks like Houraisan Kaguya wins this game!", ME.YAY, SPRITEPOS.LEFT, s_eienteihall2, function() {music_set(mus.null)}),
	txt("Though Mokou's effort was valiant, it could not stand up to the special skills of the Princess herself!", ME.YAY),
	txt("Are you kidding me!? You're gonna allow THAT!?", MOKOU.REALLYMAD, SPRITEPOS.CENTER),
	txt("It wasn't disallowed in the rules, so yes.", ME.HEHE),
	txt("...", MOKOU.HMPH),
	txt("Don't be so sad, Mokou!", ME.YAY),
	txt("I'll still help you get that brick working!", ME.WINKY),
	txt("...Whatever.", MOKOU.DEF),
	txt("I hate to admit it, but kicking Kaguya's butt was really fun.", MOKOU.YAY),
	txt("Yes, I enjoyed our time together as well.", KAGUYA.DEF, SPRITEPOS.RIGHT),
	txt("These \"video games\" are intriguing, to say the least.", KAGUYA.NEUTRAL),
	txt("So, will you two be coming to the next competition?", ME.YAY),
	txt("Of course!", KAGUYA.YAY),
	txt("Fine.", MOKOU.HMPH),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN, u, function() {music_set(mus.isnight)}),
	
	ptxt(),
	
	txt("The two exchanged short goodbyes, and Mokou departed.", u, u, s_bambooupday, function() {textbox_set_type(global.textnvl)}),
	txt("Despite how quick the game went, I was happy with my efforts. Even if my impeccable romance detectors were wrong... these two had done something else for a change."),
	txt("But I was nothing if not confident in my assumption."),
	ptxt(),
	txt("Kaguya denied any feelings for Mokou, but with the same face she had when dismissing the \"impure earthlings.\""),
	txt("...A tranlucent mask."),
	txt("Mokou was a little trickier to judge, but her bouts of anger towards Kaguya seemed more like a shield than a sword."),
	txt("If I could only push them a little more, the truth would reveal itself."),
	
//	ntxt(00, u, u, u, function() {music_set(mus.autmninsects3)}),
	
	txt("Little Rabbit, where are you going?", KAGUYA.DEF, SPRITEPOS.MIDLEFT, s_eienteihall1, function() {textbox_set_type(global.textzpix)}),
	txt("Mokou's house. I'm telling her to prepare for Round 2!", ME.YAY, SPRITEPOS.MIDRIGHT),
	txt("We're gonna do a race this time.", ME.HEHE),
	txt("Ah, how splendid!", KAGUYA.YAY),
	txt("May I accompany you?", KAGUYA.WINKY),
	txt("Huh?", ME.KAAAY),
	txt("Come now, it's not that confusing! I simply wish to partake in a stroll with you. Once it's time to talk to Mokou, I shall hide my presence.", KAGUYA.DEF),
	txt("We'll be killing two fairies with one spellcard, the way I see it.", KAGUYA.YAY),
	txt("I see...", ME.HEHE),
	txt("Is something funny?", KAGUYA.NEUTRAL),
	txt("Nope!", ME.DEF),
	txt("Let's go then!", ME.DEF),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("The outside air was even more refreshing than usual.", u, u, s_bambooday2, function() {textbox_set_type(global.textnvl)}),
	txt("Maybe it was the presence of Kaguya, or the destination we had in mind, but I could feel nothing but calm as we walked through the trees."),
	txt("For Kaguya, it seemed a different story. There was a strange tension in her movements, and she seemed to always be looking up."),
	
	txt("So, have you found anything cool recently?", ME.DEF, SPRITEPOS.MIDLEFT, s_bambooday, function() {textbox_set_type(global.textzpix)}),
	txt("Ahh... several things. The red-white shrine maiden allowed me to ride her turtle. Genji, his name was?", KAGUYA.DEF, SPRITEPOS.MIDRIGHT),
	txt("As for possessions, that young vampire over the lake gave me a bottle of vintage wine last week. It's roughly 500 years old.", KAGUYA.DEF),
	txt("Woah!", ME.POG),
	txt("Beautiful, isn't it? I would like to keep it as a collectible, but... the thought of drinking it is just too enticing!", KAGUYA.FUFUFU),
	txt("Why not save it for a special occassion?", ME.WINKY),
	txt("Like what?", KAGUYA.NEUTRAL),
	txt("Like a 2000th birthday, or a marriage...", ME.DEF),	
	txt("Or for the end of the Clash of the Moon and the Sun.", ME.SMUG),
	txt("Fufufu... Little Rabbit, that just may work.", KAGUYA.FUFUFU),
	txt("Mokou might not appreciate the value of such a celebration.", KAGUYA.DEF),
	txt("I think she will.", ME.HEHE),
	txt("...", KAGUYA.NEUTRAL),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("Kaguya's silence rang through the Bamboo Forest for far too long.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("As we approached Mokou's home, even I started getting anxious."),
	txt("But when we got there, our ears picked up something unexpected.", u, u, s_mkhsdy),
	txt("Mokou was talking to someone. She sounded excited, almost stumbling over her words."),
	txt("The other person spoke occasionally, and we could recognize her voice immediately."),
	ptxt(),
	txt("Keine Kamishirasawa. A teacher in the Human Village, and a friend of Mokou's."),
	txt("I had come across her several times during my trips there, but never seen her in the Bamboo Forest."),
	txt("She came across as very nice when we met, and once she was even walking alongside Mokou."),
	ptxt(),
	txt("We waited outside the house. It's not eavesdropping if you're still deciding whether to enter, right?"),
	
	ptxt(),	
	txt("I've been finding so much cool stuff recently! Like-- oh my gosh, Keine. Look at this thing!", MOKOU.DEF),
	txt("Oh? What's that?", KEINE.DEF),
	txt("It's the Brick! It's this little thing with a screen, like a puppet show. But you control the hero!", MOKOU.DEF),
	txt("Really? That's incredible!", KEINE.DEF),
	txt("May I see it?", KEINE.DEF),
	txt("Be my guest!", MOKOU.DEF),
	
	ptxt(),
	txt("Oh, before we get too caught up in that...", KEINE.DEF),
	txt("I made you lunch!", KEINE.DEF),
	txt("Heh... Keine, you really don't have to.", MOKOU.DEF),
	txt("I do, in fact. You don't properly feed yourself.", KEINE.DEF),
	txt("It's fine. I can just burn myself alive if I'm that hungry. I'll just resurrect, and have a full stomach again!", MOKOU.DEF),
	txt("You don't gotta worry yourself so much.", MOKOU.DEF),
	txt("...", KEINE.DEF),
	txt("Ah... sorry, that's kinda morbid.", MOKOU.DEF),
	txt("Mokou, please just eat.", KEINE.DEF),
	ptxt(),
	txt("...", MOKOU.DEF),	
	txt("...Thank you.", MOKOU.DEF),
	txt("It means a lot to me.", MOKOU.DEF),
	ptxt(),
	txt("They stopped talking for a bit. All I could hear was some faint music and Mokou eating."),

	
	txt("...", KAGUYA.WAAH, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("That's it. Kaguya, you go hide.", ME.NEUTRAL, SPRITEPOS.MIDLEFT),
	txt("Alright.", KAGUYA.AWW),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	
	ntxt(230, u, u, u, function() {audio_play_sound(snd_knocking_a_wooden_door1, 0, false)}),
	ntxt(45, MOKOU.DEF, SPRITEPOS.RIGHT, u, function() {audio_play_sound(snd_bath_door_O, 0, false)}),
	
	
	
	ntxt(00, MOKOU.DEF, SPRITEPOS.RIGHT),
	txt("Hey, Mokou!", ME.YAY),
	txt("Oh hey. Nice to see you, Princess.", MOKOU.DEF),
	
	ptxt(),
	txt("Keine sat inside the house, brick in one hand. She waved at me, and I waved back.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	
	txt("Don't mind me. I'm only here to deliver a message.", ME.DEF, u, u, function() {textbox_set_type(global.textzpix)}),
	txt("Mokou, Round 2 of the contest is tomorrow noon.", ME.HEHE),
	txt("Throwing it on me once again, aren't you?", MOKOU.SMUG),
	txt("But this time, it's...", ME.HEHE),
	txt("Cooking!", ME.YAY),
	txt("Each contestant will cook only one item.", ME.DEF),
	txt("You'll be deciding each dish for yourself, so make sure you have a plan and the necessary ingredients.", ME.DEF),
	txt("Oh, and no magic allowed.", ME.DEF),
	txt("Sounds horrible.", MOKOU.NEUTRAL),
	txt("I'm in.", MOKOU.DEF),
	txt("Yay!", ME.DEF),
	txt("Anything else you have to say?", MOKOU.NEUTRAL),
	txt("Hmm... only a question.", ME.HEHE),
	txt("\(Is Keine your girlfriend?\)", ME.SMUG),
	txt("Guh--", MOKOU.SURPRISED),
	txt("That's none of your business.", MOKOU.HMPH),
	txt("If you say so~~", ME.HEHE),
	txt("Well, I'm off now. Ta-ta!", ME.YAY),
	txt("See you later.", MOKOU.DEF),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("As I slowly walked away, I could hear a little bit of talking coming from Mokou's house.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	ptxt(),
	txt("Mokou, you never told me about this! That's so interesting!", KEINE.DEF),
	txt("It's nothing special, really. Just games with a friend.", MOKOU.DEF),
	//woah! kaguya is a friend!?!?!?
	txt("In this case, I should give you some much-needed training!", KEINE.DEF),
	txt("Keine, I can cook just fine.", MOKOU.DEF),
	txt("\"Just fine\" isn't enough in a competition. You'll be facing the best of the best!", KEINE.DEF),
	txt("Somehow, I doubt it.", MOKOU.DEF),
	
	
	ntxt(0070, u, u, s_bambooday, function() {textbox_set_type(global.textzpix)}),
	txt("Hey, Kaguya.", ME.DEF, SPRITEPOS.LEFT),
	txt("Hello.", KAGUYA.NEUTRAL, SPRITEPOS.CENTER),
	txt("Sorry I changed my mind on what we would do.", ME.WINKY),
	txt("It's no issue at all. I'm an excellent cook, you see.", KAGUYA.FUFUFU),
	txt("If you say so.", ME.HEHE),

	txt("Ah... Little Rabbit.", KAGUYA.NEUTRAL),
	txt("Hm?", ME.NEUTRAL),
	txt("What was with Mokou today?", KAGUYA.NEUTRAL),
	txt("Her voice was so happy, so relaxed... she seemed like a different person.", KAGUYA.NEUTRAL),
	txt("Is she really like that when Keine's around?", KAGUYA.AWW),
	txt("...", ME.DISAPOINT),
	txt("She's like that most of the time.", ME.NEUTRAL),
	txt("I see...", KAGUYA.WAAH),
	
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("Our walk to the House of Eternity was slow. Too slow.", u, u, s_bambooupday, function() {textbox_set_type(global.textnvl)}),
	txt("This time, Kaguya was always looking down."),	
	
	txt("Hey, Kaguya. What's in the sky right now?", ME.DEF, u, u, function() {textbox_set_type(global.textzpix)}),
	txt("The sun. Clouds. Fairies.", KAGUYA.DEF),
	txt("What else?", ME.DEF),
	txt("...The moon.", KAGUYA.DEF, u, s_daymoon),
	txt("Yes.", ME.DEF),
	txt("The moon is in the sky today, like almost every other day.", ME.DEF),
	txt("We think the day is the time of sun, and night is when the moon comes out. But that's only because it's easier to see the moon at night.", ME.DEF),
	txt("In reality, they aren't separate at all. You can see them together all the time.", ME.DEF),
	txt("Little Rabbit, I already know that.", KAGUYA.DEF),
	txt("Do you?", ME.DEF),
	txt("...", KAGUYA.DEF),
	
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(199, ME.DEF, SPRITEPOS.HIDDEN, s_black),
	
	txt("Ladies and ladies, welcome to the second ever CLASH OF THE MOON AND THE SUN!!", ME.YAY, SPRITEPOS.CENTER, s_eienteiroom1, function() {music_set(mus.glossary)}),
	txt("An event where we make your undying wishes come true!", ME.WINKY),
	ntxt(033, u, u, u, function() {audio_play_sound(snd_clapping_alone1, 0, false)}),
	txt("We have gathered our two fine contestants here today for the second greatest competition in the whole House of Eternity!", ME.DEF),
	ntxt(00, KAGUYA.YAY, SPRITEPOS.RIGHT),
	txt("Houraisan Kaguya,", ME.DEF),
	ntxt(00, MOKOU.DEF, SPRITEPOS.LEFT),
	txt("And Fujiwara no Mokou!", ME.DEF),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	txt("And as our judges today, we have...", ME.HEHE),
	ntxt(00, KANA.DEF, SPRITEPOS.LEFT),
	ntxt(00, REISEN.YAY, SPRITEPOS.RIGHT),
	txt("Kana Anaberal and Reisen Udongein Inaba!!", ME.YAY),
	txt("For you see, our competition today is not simply a matter of sport. It's one of creation!", ME.DEF),
	ntxt(00, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, REISEN.DEF, SPRITEPOS.HIDDEN),
	txt("Our contestants will be making one dish of their choice, made in this kitchen!", ME.DEF, SPRITEPOS.HIDDEN, s_kitchen),
	txt("They will be judged by Kana, Reisen, and I, on a ten-point scale. Whoever has the most points wins!", ME.DEF),
	
	txt("So, what will you two be making today?", ME.YAY, SPRITEPOS.CENTER, s_eienteiroom1),
	txt("Yakitori.", MOKOU.YAY, SPRITEPOS.LEFT),
	txt("Fufufu... Grilled chicken on a stick? Mokou, how unambitious.", KAGUYA.FUFUFU, SPRITEPOS.RIGHT),
	txt("Oh yeah? Then what's your item?", MOKOU.HMPH),
	txt("Chocolate-chip cookies!", KAGUYA.WINKY),
	txt("*Wow.*", MOKOU.SMUG),
	txt("What is that look for? They are a high-class delicacy overseas.", KAGUYA.DEF),

	txt("Oh, and by the way... you each have ten minutes!", ME.WINKY),
	txt("TEN!?", MOKOU.SURPRISED),
	txt("Ten. Also, the timer started about a minute ago. Get to it!", ME.YAY),
	txt("Will do!", KAGUYA.YAY),
	txt("I swear...", MOKOU.HMPH),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(90, ME.DEF, SPRITEPOS.HIDDEN, s_kitchen, function() {audio_play_sound(snd_running_in_a_house, 0, false)}),
	
	txt("Okay, we have the thighs and vegetables right here...", MOKOU.NEUTRAL, SPRITEPOS.MIDRIGHT),
	txt("Now first is the flour, then the sugar...", KAGUYA.FUFUFU, SPRITEPOS.LEFT),
	//sound of egg cracking, mixing up
	txt("~~Humpty Dumpty sat in a carton~~#~~Humpty Dumpty was cracked apart~~", KAGUYA.DEF, u, u, function() {audio_play_sound(snd_cracking_egg1, 0, false)}),
	txt("~~And all the Princesses and all the bunnies~~#~~Ate Humpty up with an overjoyed grin!~~", KAGUYA.YAY),
	txt("That didn't even rhyme.", MOKOU.SMUG),
	txt("It's experimental poetry. You wouldn't understand.", KAGUYA.FUFUFU),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.LEFT),
	ntxt(0, REISEN.DEF, SPRITEPOS.RIGHT),
	
	txt("Hey, look at Kaguya! She's mixing those ingredients like a champ!", ME.YAY, SPRITEPOS.CENTER, s_eienteiroom1),
	ntxt(00, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	txt("Oh no! The batter's gotten into my hair!", KAGUYA.SHOCKED, SPRITEPOS.LEFT, s_kitchen),
	txt("I need to clean it this instant!", KAGUYA.AWW),
	ntxt(40, KAGUYA.DEF, SPRITEPOS.HIDDEN, u, function() {audio_play_sound(snd_running_in_a_house, 0, false)}),
	txt("...", MOKOU.BRUH, SPRITEPOS.MIDRIGHT),
	txt("Well, whatever gives me more time.", MOKOU.YAY),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	
	ntxt(0, KANA.NEUTRAL, SPRITEPOS.LEFT),
	ntxt(0, REISEN.DEF, SPRITEPOS.RIGHT),	
	txt("Woah! Do you see those knife skills from Mokou?", ME.POG, SPRITEPOS.CENTER, s_eienteiroom1, function() {audio_play_sound(snd_cutting_a_onion_speedy, 0, false)}),
	txt("She's cutting the chicken so quickly!", ME.POG),
	ntxt(0080),
	ntxt(0030, u, u, u, function() {audio_play_sound(snd_cutting_with_a_katana1, 0, false)}),
	ntxt(0000, KANA.SCARED, SPRITEPOS.LEFT),
	ntxt(0040, REISEN.WOAH, SPRITEPOS.RIGHT),
	txt("And she... lost a finger.", ME.WHAA),
	txt("Should we...", KANA.SCARED),
	txt("N-nah, it's fine! A little blood would just... add to the flavor!", ME.KAAAY),	
	ntxt(00, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),
	txt("Alright, now for the sauce. First step is the sake... then soy sauce, and...", MOKOU.NEUTRAL, SPRITEPOS.MIDLEFT, s_kitchen),
	txt("There we go, I'm all clean now!", KAGUYA.DEF, SPRITEPOS.MIDRIGHT),
	txt("Now where were we...", KAGUYA.DEF),	
	txt("Halfway through frying the chicken, your majesty.", MOKOU.SMUG),
	txt("Yes, I can see tha-- |w0020 |- ", KAGUYA.MAD),
	txt("--Mokou, your finger!", KAGUYA.SHOCKED),
	txt("Oh, this?", MOKOU.NEUTRAL),
	txt("Don't worry about it. I'm not gonna let any blood on the food.", MOKOU.DEF),	
	txt("Doesn't it hurt?", KAGUYA.AWW),
	txt("Of course. But...", MOKOU.NEUTRAL),
	txt("Just one teensy second...", KAGUYA.FUFUFU),
	ntxt(0030, u, u, u, function() {audio_play_sound(snd_magic7, 0, false)}),
	txt("There we go!", KAGUYA.YAY),
	txt("I cast a spell to make it heal instantly. All better now?", KAGUYA.YAY),
	txt("...", MOKOU.NEUTRAL),
	txt("Yeah.", MOKOU.YAY),
	
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	txt("Aww...", KANA.YAY, SPRITEPOS.LEFT, s_eienteiroom1),
	txt("So, Judge Kana, how are you looking foreward to eating these lasses' delicious food?", ME.DEF, SPRITEPOS.CENTER),
	txt("I'm scared for my life, honestly.", KANA.NEUTRAL, SPRITEPOS.LEFT),
	txt("A very understandable reaction! How about you, Judge Reisen?", ME.YAY),
	txt("Who even cares how good it is? I'm so hungry, I could eat anything. Even Kana's cooking!", REISEN.UGGH, SPRITEPOS.RIGHT),
	txt("Hey, take that back! I'm a great cook!", KANA.MAD),
	txt("Kana, you are a wonderful, amazing, beautiful person...", REISEN.YAY),
	txt("Who cooks.", REISEN.SMUG),
	ntxt(0030),
	
	ntxt(00, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, REISEN.DEF, SPRITEPOS.HIDDEN),
	txt("ONE MINUTE LEFT!", ME.DEF, SPRITEPOS.HIDDEN, s_kitchen),
	
	txt("Oh, you are so screwed.", MOKOU.SMUG, SPRITEPOS.CENTER),	
	txt("Pop these in the oven here, and... done!", KAGUYA.DEF, SPRITEPOS.LEFT),
	txt("What the--", MOKOU.SURPRISED),
	txt("They were only in there for a second!", MOKOU.HMPH),
	txt("Fufufu. I simply manipulated the oven's eternity. Inside that oven, ten minutes just passed.", KAGUYA.FUFUFU),
	txt("What about the no-magic rule?", MOKOU.BRUH),
	txt("That was a rule?", KAGUYA.NEUTRAL),
	txt("...", MOKOU.SURPRISED),
	txt("Oh, sorry. I didn't mention that, did I?", ME.WINKY, SPRITEPOS.RIGHT),
	txt("In that case, let's just throw that rule out the window, okay?", ME.DEF),
	txt("Wait, that's totally wrong! Rules shouldn't just be broken because you screwed up!", MOKOU.MAD),
	txt("But you were okay with your finger being healed.", ME.DEF),
	txt("That was-- |- ", MOKOU.REALLYMAD, u, u, function() {audio_play_sound(snd_kitchen_timer1, 0, false)}),
	txt("AAAAND TIME'S UP!!", ME.YAY),
	txt("Contestants, bring your dishes to the table.", ME.HEHE),
	
	txt("...", MOKOU.HMPH),
	txt("...", KAGUYA.FUFUFU),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	txt("First up is Fujiwara no Mokou's yakitori!", ME.YAY, SPRITEPOS.HIDDEN, s_yaki),
	txt("Mokou, how was your experience making this fine dish?", ME.DEF),
	txt("Amazing, except for the fact that I had zero time to actually cook it.", MOKOU.NEUTRAL),
	txt("Good to know!", ME.YAY),
	//nomnomnom sounds
	
	txt("Hmm...", ME.DISAPOINT, SPRITEPOS.CENTER, s_eienteiroom1),
	txt("Judge Reisen, what do you think of the meat?", ME.DEF),
	txt("It's undercooked, as expected.", REISEN.UGGH, SPRITEPOS.RIGHT),
	txt("I see...", ME.NEUTRAL),
	txt("Judge Kana, what do you think of the meat?", ME.DEF),
	txt("I love the sauce! It's very tasty!", KANA.YAY, SPRITEPOS.LEFT),
	txt("Judge Kana, what do you think of the meat?", ME.DEF),
	txt("The veggies were cut really well, and they feel great to chew.", KANA.DEF),
	txt("Judge Kana, what do you think of the meat?", ME.DEF),
	txt("...It's not dry.", KANA.NEUTRAL),
	txt("Amazing input, Judge Kana!", ME.YAY),
	txt("Now, let's show our scores in 3, 2, 1...", ME.DEF),
	
	//drumroll music
	ntxt(0060, REISEN.JDGMOKU, SPRITEPOS.RIGHT),
	ntxt(0060, KANA.JDGMOKU, SPRITEPOS.LEFT),
	ntxt(0060, ME.JDGMOKU, SPRITEPOS.CENTER),
	
	txt("That's a 3, a 7, and a 6! You get a total of 16 points!", ME.WINKYHEART),
	txt("A bit generous, honestly...", MOKOU.NEUTRAL),
	
	ntxt(000, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	
	txt("Next is Houraisan Kaguya's chocolate chip cookies!", ME.YAY, SPRITEPOS.HIDDEN, s_cooky),
	txt("Pray tell, how did these go for you?", ME.DEF),
	txt("Absolutely swimmingly.", KAGUYA.FUFUFU),
	//nomnom sounds
	
	txt("Ooh...", ME.HEHE, SPRITEPOS.CENTER, s_eienteiroom1),
	txt("Judge Kana, what do you think of these?", ME.DEF),	
	txt("These cookies are perfect!", KANA.YAY, SPRITEPOS.LEFT),
	txt("They have such a nice gooeyness to them on the inside, that really elevates them for me.", KANA.DEF),
	txt("It must be because of the chocolate chips, and those create the most immaculate palette of flavors ever!", KANA.COCKY),
	txt("Oh my, what high praise! Judge Reisen, what's your opinion?", ME.YAY),
	txt("It's good.", REISEN.DEF, SPRITEPOS.RIGHT),
	txt("Splendiferous feedback, Judge Reisen!", ME.YAY),
	txt("Now, for our final scoring...", ME.WINKY),
	ntxt(000, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	txt("Say goodbye to your dignity, Fujiwara no Mokou.", KAGUYA.FUFUFU, SPRITEPOS.MIDLEFT, s_kitchen),
	txt("You kidding me? I did that the moment I agreed to this \"competition.\"", MOKOU.HMPH, SPRITEPOS.MIDRIGHT),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	
	txt("In 3... 2... 1........~~~", ME.DEF, SPRITEPOS.CENTER, s_eienteiroom1),
		
	///drumroll music
	ntxt(0100, REISEN.JDGKAGU, SPRITEPOS.RIGHT),
	ntxt(0100, KANA.JDGKAGU, SPRITEPOS.LEFT),
	ntxt(0200, ME.JDGKAGU, SPRITEPOS.CENTER),
	txt("And Kaguya gets 15 points! Sorry, but it seems you've been bested in this round!", ME.DEF),
	ntxt(000, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	txt("Wh-what do you mean!?", KAGUYA.SHOCKED, SPRITEPOS.CENTER, s_kitchen),
	txt("I did them so well! Those cookies were perfect!", KAGUYA.SHOCKED),
	txt("Don't you know?", ME.HEHE, SPRITEPOS.RIGHT),
	txt("I hate cookies.", ME.SMUG),
	txt("You...", KAGUYA.MAD),
	txt("...Wow.", MOKOU.NEUTRAL, SPRITEPOS.LEFT),
	txt("How does it feel to get screwed over by arbitrary bullcrap?", MOKOU.SMUG),
	txt("Horrible, thank you very much!", KAGUYA.MAD),
	txt("Not that your food was any good.", KAGUYA.MAD),
	txt("It would've been if I had as much time as you!", MOKOU.MAD),
	ntxt(00, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	ntxt(00, ME.DEF, SPRITEPOS.HIDDEN),	
	txt("\(Hey, why are you giving them so much trouble?\)", KANA.BRUH, SPRITEPOS.LEFT, s_eienteiroom1),	
	txt("\(It ain't just trouble, Kana. This is all part of my master plan to bring them closer together!\)", ME.HEHE, SPRITEPOS.CENTER),
	txt("\(Are you sure they're not just going to get angry at you?\)", REISEN.DEF, SPRITEPOS.RIGHT),
	txt("\(Not at all.\)", ME.HEHE),
	txt("\(I'm putting my life at risk for this!\)", ME.WINKY),
	ntxt(000, REISEN.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN, u, function() {music_set(mus.null)}),
	ptxt(),
	txt("While the two immortals argued, us judges started cleaning everything up.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("Kana and Reisen had to leave immediately, but I stuck around to see Mokou off."),
	txt("Just as I was about to say goodbye...", u, u, s_kitchen, function() {music_set(mus.isnight)}),
	
	ntxt(00, KAGUYA.YAY, SPRITEPOS.RIGHT),
	txt("Hey, Princess?", MOKOU.NEUTRAL, SPRITEPOS.LEFT, u, function() {textbox_set_type(global.textzpix)}),
	txt("Yeah?", ME.YAY, SPRITEPOS.CENTER),
	txt("Do you mind if I stay here a little longer?", MOKOU.DEF),
	txt("For what?", ME.KAAAY),
	txt("There's a small bit of dough still left, so...", KAGUYA.DEF),
	txt("...We've decided to bake a few more cookies.", MOKOU.YAY),
	txt("Together.", KAGUYA.YAY),
	txt("...", ME.POG),
	txt("Go for it!", ME.YAY),
	txt("Thanks. We'll be done in a jiffy, I promise.", MOKOU.DEF),
	txt("By the way, don't get the wrong idea. I'm only doing this to gauge Kaguya's skills for our next battle.", MOKOU.HMPH),
	txt("\(Sure you are.\)", ME.HEHE),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	
	txt("Alright, so you roll these into balls... and I'll take these ones.", MOKOU.DEF),
	txt("Splendid.", KAGUYA.FUFUFU),
	
	ntxt(000, KAGUYA.DEF, SPRITEPOS.HIDDEN),
		
	txt("Huh, you're really good at this.", MOKOU.NEUTRAL, SPRITEPOS.MIDLEFT),
	txt("Don't flatter me, Mokou. Your ball-rolling skills are simply flawed.", KAGUYA.FUFUFU, SPRITEPOS.MIDRIGHT),
	txt("I expected more from you, to be quite honest.", KAGUYA.FUFUFU),	
	txt("Come on, gimme a break! I haven't done this in 384 years!", MOKOU.MAD),
	txt("Isn't this the same as creating fireballs?", KAGUYA.DEF),
	txt("Not at all! Fire is far more malleable than this. For these, you need a different amount of pressure.", MOKOU.HMPH),
	
	txt("Oh my, Mokou! That one you made...", KAGUYA.DEF),
	txt("Hm?", MOKOU.BRUH),
	txt("Looks a little like a heart, doesn't it?", KAGUYA.DEF),
	txt("If you say so.", MOKOU.HMPH),
	txt("I'll go fix it now-- |w0040 |- ", MOKOU.NEUTRAL),
	txt("No no, keep it that way. It adds a little spice!", KAGUYA.YAY),
	txt("...", MOKOU.SAD),
	txt("Yeah. You're right.", MOKOU.SADSMILE),
	
	txt("Put these in the oven, and... done!", KAGUYA.YAY),
	txt("Damn, you're really making me jealous with those powers. What the heck did you do to earn them?", MOKOU.DEF),
	txt("Be a Lunarian Princess. Every one of us is born with some unique power.", KAGUYA.YAY),
	txt("Beautiful little snowflake, aren't ya? Just to be expected from a lunatic like you.", MOKOU.SMUG),
	txt("You are too, Mokou.", KAGUYA.YAY),
	ntxt(000, MOKOU.SURPRISED, SPRITEPOS.MIDLEFT),
	txt("A beautiful snowflake.", KAGUYA.WINKYHEART),
	txt("A--ahh...", MOKOU.LOVEYSAD),
	ntxt(000, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, MOKOU.DEF, SPRITEPOS.HIDDEN),
	
	txt("Let us eat these cookies, before they get cold and hard.", KAGUYA.FUFUFU, SPRITEPOS.RIGHT, s_eienteiroom1),
	//yes she could use he powers to freeze time for them ssshshhsshhshshhshs
	//could prob mention that in dialogue but uhggg itd be so awkward the way its written nowwwwww
	txt("Ooh, they look great!", ME.DEF, SPRITEPOS.CENTER),
	txt("Can I have some?", ME.YAY),
	txt("Don't you hate cookies?", MOKOU.BRUH, SPRITEPOS.LEFT),
	txt("Yes.", ME.WINKY),
	ntxt(000, MOKOU.NEUTRAL, SPRITEPOS.LEFT),
	ntxt(000, KAGUYA.NEUTRAL, SPRITEPOS.RIGHT),
	
	//nomnomnom sounds
	
	txt("...", ME.DISAPOINT),
	txt("...", ME.NEUTRAL),
	txt("I love them.", ME.DEF),
	txt("You two get a 10 out of 10!", ME.JDGALL),
	txt("Really!?", KAGUYA.SHOCKED),
	txt("How!?", MOKOU.SURPRISED),
	txt("Don't you know?", ME.HEHE),
	txt("Everything tastes sweeter when it's made with love!", ME.WINKYHEART),
	txt("...", KAGUYA.WOAH),
	txt("...", MOKOU.LOVEYSAD),
	ntxt(000, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("It was getting late, so both Mokou and I had to leave.", u, u, s_eienteihall3, function() {textbox_set_type(global.textnvl)}),
	txt("As we walked out, the two seemed to act strange. I couldn't put my finger on it for the longest time, but then realized. It was just like how Kana acted, way back when."),
	
	ntxt(000, ME.HEHE, SPRITEPOS.RIGHT),
	ntxt(000, KAGUYA.DEF, SPRITEPOS.CENTER),
	txt("See you two later.", MOKOU.DEF, SPRITEPOS.LEFT, s_eientei2, function() {textbox_set_type(global.textzpix)}),
	txt("Thank you for coming to this. It was very fun.", KAGUYA.DEF),
	txt("It was.", MOKOU.DEF),
	txt("I really like spending time with--|w0042 |- ", MOKOU.YAY),
	txt("...", MOKOU.SURPRISED),
	txt("I... like spending time fighting you.", MOKOU.HMPH),
	txt("...", KAGUYA.LOVEY),
	txt("I'm off.", MOKOU.NEUTRAL),
	txt("Goodnight, Mokou.", KAGUYA.YAY),
	
	ntxt(0110, MOKOU.DEF, SPRITEPOS.HIDDEN),
	
	txt("...", ME.NEUTRAL),
	txt("Kaguya... what do you wish for with Mokou?", ME.NEUTRAL),	
	txt("...What do you want?", ME.NEUTRAL),
	txt("I...", KAGUYA.WAAH),
	txt("I want to see Mokou happy. Like she is with Keine.", KAGUYA.DEF),
	txt("No, more than that. I want to be the one that makes her happy. And I want to be with her, happy together.", KAGUYA.YAY),
	txt("...Forever.", KAGUYA.LOVEY),
	txt("So... you love her.", ME.HEHE),
	txt("Ah--", KAGUYA.WOAH),
	txt("\"Love\" is a rather intense word...", KAGUYA.AWW),
	txt("You murder each other regularly. I don't think intensity is that taboo for you.", ME.SMUG),
	txt("It's different there.", KAGUYA.NEUTRAL),
	txt("You sure about that?", ME.SMUG),
	txt("...", KAGUYA.WAAH),
	txt("I gotta go now. My parents are gonna be real mad at me.", ME.TINYSMIRK),
	txt("I see...", KAGUYA.NEUTRAL),
	txt("Have a pleasant snooze, Little Rabbit.", KAGUYA.YAY),
	txt("You too.", ME.TINYSMIRK),
	ntxt(064, ME.DEF, SPRITEPOS.HIDDEN),
	ntxt(078, KAGUYA.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, u, u, u, function() {music_set(mus.wind1)}),
	
	ptxt(),
	txt("That night, I thought of what to do. Something was coming either way; all I could do was speed it up.", u, u, s_crescent, function() {textbox_set_type(global.textnvl)}),
	txt("The next few days went smoothly. Most of it comprised of helping out those at Eientei."),
	txt("It appeared that Kaguya and Mokou were going to fight soon."),
	ptxt(),
	txt("With that knowledge, I decided to go see Mokou.", u, u, s_mkhsnt),
	ntxt(00, KANA.NEUTRAL, SPRITEPOS.MIDRIGHT),
	txt("I asked Kana to come with me... just like old times."),
	ntxt(00, ME.HEHE, SPRITEPOS.MIDLEFT),
	txt("...I don't understand those two at all.", KANA.AWW, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("Do they like each other or not?", KANA.NEUTRAL, SPRITEPOS.MIDRIGHT),
	txt("They...", ME.DISAPOINT),
	txt("It's not that simple, is it?", KANA.AWW),
	txt("Maybe.", ME.NEUTRAL),
	ntxt(0140, u, u, u, function() {audio_play_sound(snd_knocking_a_wooden_door1, 0, false)}),
	ntxt(0180, u, u, u, function() {audio_play_sound(snd_knocking_a_wooden_door2, 0, false)}),
	txt("She's not home...?", KANA.NEUTRAL),
	txt("Hey! Over here!", MOKOU.DEF),
	ntxt(000, ME.DEF, SPRITEPOS.HIDDEN),
	ntxt(000, KANA.DEF, SPRITEPOS.HIDDEN, u, function() {music_set(mus.campfire)}),
	txt("My bad, I didn't think anyone would come over.", MOKOU.SMUG, SPRITEPOS.RIGHT, s_campfire, function() {textbox_set_type(global.textzpix)}),
	txt("Ooh! What are you doing?", ME.POG),
	txt("Making real yakitori.", MOKOU.SMUG),
	txt("Want some?", MOKOU.YAY),
	txt("Sure!", KANA.YAY),
	
	ntxt(000, KANA.YAY, SPRITEPOS.LEFT),
	txt("..."),
	txt("You two here to deliver a message?", MOKOU.DEF),
	txt("Nope!", ME.YAY, SPRITEPOS.CENTER),
	txt("Really? You just wanted to see me?", MOKOU.SMUG),
	txt("Yep!", ME.YAY),
	txt("...", MOKOU.NEUTRAL),
	txt("Okay.", MOKOU.YAY),
	ntxt(000, ME.YAY, SPRITEPOS.CENTER),
	//nomnomnom sounds
	
	txt("It's been a hot minute since I've talked to you, Kana.", MOKOU.DEF, SPRITEPOS.RIGHT),
	txt("Yeah, it has!", KANA.YAY),
	txt("You like it over there in the House of Eternity?", MOKOU.DEF),
	txt("Absolutely!", KANA.YAY),
	txt("Living with Reisen is enough to make me happy. But Kaguya and Eirin and the rabbits are really nice too!", KANA.DEF),
	txt("And there's so many interesting things to do in there. Even with all the chores, I never get bored.", KANA.YAY),
	txt("That's good to hear.", MOKOU.DEF),
	txt("Oh my gosh, these are so much better than the last ones!", KANA.YAY),
	txt("Thanks.", MOKOU.DEF),
	txt("Though that's not a very high bar to clear...", MOKOU.SMUG),
	txt("You did a great job in the competition too.", KANA.DEF),
	txt("Really now?", MOKOU.BRUH),
	txt("Yeah! I wouldn't even have any food in the oven in time!", KANA.DEF),
	txt("\(You don't use an oven for yakitori...\)", MOKOU.NEUTRAL),
	txt("Oh, speaking of. Princess, you reminded me of Kaguya back there with your dumb tricks.", MOKOU.HMPH),	
	txt("You're lucky nothing important was on the line there, or at least five of your bones would be broken right now.", MOKOU.MAD),
	txt("Ah.", ME.WHAA),
	txt("Na-hah, I'm just joshin' ya!", MOKOU.YAY),
	txt("It led to a win for me, so who am I to complain?", MOKOU.YAY),
	txt("Ah, yeah. You looked happy.", ME.YAY),
	txt("I was.", MOKOU.DEF),
	txt("...", ME.NEUTRAL),	
	txt("Do you... like Kaguya?", ME.DEF),
	txt("Hey, don't get it twisted.", MOKOU.HMPH),
	txt("Just because I have fun with her sometimes, doesn't mean I like her.", MOKOU.HMPH),
	txt("She's still my enemy. That's not gonna change.", MOKOU.HMPH),
	txt("...Why?", ME.NEUTRAL),
	txt("...", MOKOU.NEUTRAL),
	txt("She's the reason I'm like this. Stuck in this immortal body.", MOKOU.SADSMILE),
	txt("Really!? What did she do?", ME.POG),
	txt("A nosy one, aren't you?", MOKOU.SMUG),
	ntxt(0, ME.NEUTRAL, SPRITEPOS.CENTER),
	txt("...It wasn't anything she did. Just what she had.", MOKOU.SADSMILE),
	txt("Back when she first came to Earth, everyone saw her as the ever-unattainable maiden. She tempted my father with her charms, until he wanted her more than anything.", MOKOU.SAD),
	//txt("And as a kid, I thought that if I gave my father what he wanted... he might want me.", MOKOU.SAD),
	txt("When she disappeared, she left behind the Elixir of Immortality.", MOKOU.NEUTRAL),
	txt("Long story short, I ended up in the wrong place at the wrong time... and stole it for myself.", MOKOU.SADSMILE),
	txt("Ah, sorry. You don't want to hear all this sad stuff, do you?", MOKOU.NEUTRAL),
	txt("It's fine, Mokou.", KANA.YAY),
	txt("...", MOKOU.NEUTRAL),
	txt("Besides Keine, I've never told anyone all this. Certainly not like this.", MOKOU.DEF),
	txt("...Are you okay saying these things now?", KANA.AWW),
	txt("Ah, don't worry. It's in the past now. Besides, Kaguya's certainly told you all this already.", MOKOU.YAY),
	txt("She hasn't.", KANA.NEUTRAL),
	txt("...", MOKOU.NEUTRAL),
	txt("If it's in the past like you say... why are you still enemies?", ME.DISTANT),
	
	txt("To be perfectly honest... she's something to hate. When I had nothing else, hatred has kept me alive all these centuries.", MOKOU.SAD),
	txt("...", KANA.AWW),
	txt("I spent 300 years hating myself. I wanted to die, but that was impossible. So the next best thing was to keep myself hidden away, as a living mistake.", MOKOU.SAD),
	txt("For 300 years, I hated the world, and took it out on everyone I came across. And when I stopped hating, I stopped caring. I existed without living.", MOKOU.SAD),
	txt("Now, the one to hate helped cause this in the first place. What's more, she'll always be there.", MOKOU.NEUTRAL),
	txt("Whether or not she's really at fault... I hate her.", MOKOU.SAD),
	txt("I have to.", MOKOU.SADSMILE),
	txt("And sure, maybe that hatred will turn into love someday.", MOKOU.DEF),
	txt("Maybe I'll look at her one night and say a few stupid words, only to take them back a moment later.", MOKOU.DEF),
	txt("Maybe once Keine passes away, Kaguya will find me crying alone.", MOKOU.NEUTRAL),
	txt("For just one night, I'll forget who we are, and lose myself in her arms.", MOKOU.NEUTRAL),
	txt("And the morning after, we'll separate, and live through hatred once again.", MOKOU.SAD),
	txt("...", KANA.AWW),
	txt("That sounds like a very sad love.", KANA.AWW),
	txt("It does.", MOKOU.SADSMILE),
	txt("...", KANA.AWW),
	txt("Does it have to be that way?", ME.NEUTRAL),
	txt("...", MOKOU.SAD),
	txt("Beats me.", MOKOU.DEF),
	
	ntxt(0060),
	ntxt(0, ME.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, MOKOU.DEF, SPRITEPOS.HIDDEN, u, function() {music_set(mus.rainthunder1)}),
	
	ptxt(),
	txt("The next day, it rained like there was no tomorrow.", u, u, s_bamboorain, function() {textbox_set_type(global.textnvl)}),
	txt("Each hour, I looked out the window, searching for something that I didn't know existed."),
	txt("And yet... nothing happened that night."),
	txt("The full moon rose and fell without a single sound."),
	
	ptxt(),
	txt("... |w0200 |- ", u, u, s_black),
	
	ptxt(),
	txt("The night of a full moon, and a night of rain.", u, u, s_eienteihall3),
	txt("The moon shone through the clouds with a strange glow. The glow felt... nostalgic. Like something I had not felt in centuries."),
	txt("This was not the feeling I had when the Moon's emissaries came to take me back. This was... more akin to when I had first gone to Earth."),
	txt("Normally this would generate excitement from Reisen and Eirin, but the sounds seemed to cast a spell of sleep on them."),
	
	ptxt(),
	txt("Would Little Rabbit come here, I wondered? She loved the time just after it rains."),
	txt("I doubted it. From the way she described them, her parents were tired of her little adventures. She had toed the line for a long while, but she could not \"sneak out\" every day."),
	txt("Besides, I would likely not have time to lounge. Something strange was occurring."),
	txt("The House of Eternity seemed... emptier tonight. As though its soul had been plucked out and dropped somewhere."),
	txt("Each hall was total darkness, each step silent. I couldn't stand it."),
	
	txt("Hey Kaguya.", KANA.DEF, SPRITEPOS.LEFT, u, function() {textbox_set_type(global.textzpix)}),
	txt("Good night.", KME.NEUTRAL, SPRITEPOS.RIGHT),
	txt("I'm bored. Wanna play Chesshogi?", KANA.YAY),
	txt("I shall pass tonight. It's about time to leave.", KME.NEUTRAL),
	txt("Someone is waiting for me.", KME.FUFUFU),
	txt("...I see.", KANA.NEUTRAL),
	txt("Good luck.", KANA.AWW),
	txt("...", KME.AWW),
	
	ntxt(0, KANA.DEF, SPRITEPOS.HIDDEN),
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ptxt(),
	txt("Without a sound, I left the House of Eternity.", u, u, s_fullmoon1, function() {textbox_set_type(global.textnvl)}),
	txt("I flew through the countless trees, letting the moon guide me."),
	txt("At some point during my search, the rain stopped."),
	ntxt(0, MOKOU.SAD, SPRITEPOS.MIDLEFT),
	txt("And shortly after that... I found her."),
	txt("The one who wished to see me."),
	ntxt(0, u, u, u, function() {music_set(mus.lovewar)}),
	
	txt("Hello there, Mokou.", KME.FUFUFU, SPRITEPOS.MIDRIGHT, u, function() {textbox_set_type(global.textzpix)}),
	txt("Hey.", MOKOU.NEUTRAL),
	txt("You ready?", MOKOU.COCKY),
	txt("If you mean to fight...", KME.AWW),
	txt("Y-yes. I... believe so.", KME.WAAH),
	txt("What's gotten you so down?", MOKOU.DEF),
	txt("Did the rain ruin your precious hair?", MOKOU.SMUG),
	txt("I'm not here to fight. I just need tell you something.", KME.NEUTRAL),
	txt("Mokou, I...|w0060 I lo-- |-", KME.AWW),
	txt("Save your jokes for afterwards.", MOKOU.HMPH),
	txt("Or even better, don't make them at all.", MOKOU.HMPH),
	txt("It's not...", KME.WAAH),
	txt("I'm not in the mood for it, Kaguya.", MOKOU.MAD),
	txt("...I see.", KME.NEUTRAL),
	txt("Then I shall fight you to the best of my abilities!", KME.COCKY),
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(200, MOKOU.DEF, SPRITEPOS.HIDDEN),
	])endevent = function() {
		c_getitembyid(ITEMS.UNDERTALE).battling = true;
		global.spells[DIFFICULTY.HARD].mokou = [global.spellnames[?"Cycle of Death and Rebirth"]];
		c_makeboss(global.bosses.mokou, [SPELL.CARD]);
	}
	
}
function txt_kagumokumid1() {
	msg = [
	//boom bam wapposhy pow
	//AKA FIRST SPELLCARD
	
	txt("What's with you tonight? You're barely attacking me at all!", MOKOU.MAD, SPRITEPOS.LEFT, s_fullmoon1),
	txt("One thing first...", KME.DEF, SPRITEPOS.CENTER),
	txt("I think you're smoking hot.", KME.FUFUFU),
	txt("Wow. Never heard that one before.", MOKOU.HMPH),
	txt("Did the Princess tell you that one?", MOKOU.NEUTRAL),
	txt("Yes, actually.", KME.YAY),
	txt("Thought so.", MOKOU.NEUTRAL),
	txt("...?", KME.NEUTRAL),
	txt("Don't you dare say it again.", MOKOU.MAD),
	txt("I can handle that from *anyone* but you.", MOKOU.HMPH),
	txt("...", KME.AWW),
	
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(100, MOKOU.DEF, SPRITEPOS.HIDDEN),
	];endevent = function() {
		c_getitembyid(ITEMS.UNDERTALE).battling = true;
		global.spells[DIFFICULTY.HARD].mokou = [global.spellnames[?"Waltz of the Moon and Sun"]];
		c_makeboss(global.bosses.mokou, [SPELL.CARD]);
	}
	//2ND SPELLCARD
	//BANGBANG PICHUUN WAPOOSH BAZZAP
}
function txt_kagumokumid2() {
	
	msg = [
	txt("Your attacks aren't doing anything.", KME.FUFUFU, SPRITEPOS.LEFT, s_fullmoon1),
	txt("Why don't we try something else?", KME.FUFUFU),
	txt("I hear the Scarlet Devil is throwing a party soon. Why not attend it together?", KME.YAY),
	txt("That just sounds like a date.", MOKOU.HMPH, SPRITEPOS.RIGHT),
	txt("It does.", KME.FUFUFU),
	txt("I'll pass, thanks.", MOKOU.NEUTRAL),
	txt("Mokou, nothing is going to change if we keep doing this.", KME.AWW),
	txt("...", MOKOU.SURPRISED),
	txt("Have our fights gotten boring to you?", MOKOU.NEUTRAL),
	txt("Not quite yet.", KME.NEUTRAL),
	txt("But I want something more.", KME.AWW),
	txt("...", MOKOU.LOVEYSAD),
	
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(100, MOKOU.DEF, SPRITEPOS.HIDDEN),
	]endevent = function() {
		c_getitembyid(ITEMS.UNDERTALE).battling = true;
		global.spells[DIFFICULTY.HARD].mokou = [global.spellnames[?"1000 Years of Hatred"]];
		c_makeboss(global.bosses.mokou, [SPELL.CARD]);
	}
}
function txt_kagumokumid3() {
	//3RD SPELLCARD
	//BACHOOM WAPISH SCHKWANACH
	msg = [
	txt("For a while, I've wished to get to know you, Mokou. We've only interacted in these battles, but you have so many sides to you.", KME.DEF, SPRITEPOS.MIDLEFT, s_fullmoon1),
	txt("I want to see and understand you as a person.", KME.YAY),
	txt("...", MOKOU.LOVEYSAD, SPRITEPOS.MIDRIGHT),
	txt("S-stop lying. It's not like you see us as equals-- you keep calling me a \"foolish earthling\" every other blow.", MOKOU.HMPH),
	txt("How could you possibly understand me if that's what I am to you?", MOKOU.MAD),
	txt("...Mokou, the moon has been far away from me for a long time. I've learned to live among these \"earthlings.\"", KME.NEUTRAL),
	txt("The distinction between you and I was arbitrary from the start. I kept the pretense up for the sake of tradition, but...", KME.AWW),
	txt("I'm a human, just like you.", KME.LOVEY),
	txt("...I see.", MOKOU.SAD),
	txt("I spent all these years cooped up inside a cage of my own making. But now that I have finally gone out into this \"impure\" Earth...", KME.DEF),
	txt("It's better than I could've imagined.", KME.YAY),
	txt("And you're the most beautiful part of it.", KME.LOVEY),
		
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(100, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	
	]endevent = function() {
		c_getitembyid(ITEMS.UNDERTALE).battling = true;
		global.spells[DIFFICULTY.HARD].mokou = [global.spellnames[?"Loved Ones Passing Us By"]];
		c_makeboss(global.bosses.mokou, [SPELL.CARD]);
	}
}
function txt_kagumokumid4() {
	//4TH SPELLCARD
	//BACHIKUUUU
		msg = [
	ntxt(0, KME.WAAH, SPRITEPOS.RIGHT, s_fullmoon1),
	txt("Please, Kaguya...", MOKOU.LOVEYSAD, SPRITEPOS.LEFT),
	txt("I can't.", MOKOU.LOVEYSAD),
	txt("Do you know how much time I spent in isolation, or being chased, or in constant battles?", MOKOU.LOVEYSAD),
	txt("Too much. Far too much.", MOKOU.SAD),
	txt("The cycle of death and rebirth will never stop, no matter how much I want it to.", MOKOU.SAD),
	txt("And it was all because of you!", MOKOU.REALLYMAD),
	txt("I know.", KME.AWW),
	txt("I know, and I'm sorry.", KME.WAAH),
	txt("Sorry for keeping the Elixir of Immortality and throwing it away so recklessly.", KME.WAAH),
	txt("Sorry for hiding myself away from the consequences.", KME.WAAH),
	txt("Sorry for leaving you all alone.", KME.CRY),
	]
	endevent = function() {
		c_getitembyid(ITEMS.UNDERTALE).battling = true;
		global.spells[DIFFICULTY.HARD].mokou = [global.spellnames[?"...And So We Continued to Stay on This Beautiful Earth"]];
		c_makeboss(global.bosses.mokou, [SPELL.CARD]);
	}
}
	//FINAL SPELLCARD
	//TERIYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
function txt_kagumokuend() {
	msg = [
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN, s_fullmoon1),
	ntxt(100, MOKOU.DEF, SPRITEPOS.HIDDEN),	
	
	txt("Kaguya...", MOKOU.LOVEYSAD, SPRITEPOS.MIDLEFT),
	txt("Mokou, I know.", KME.AWW, SPRITEPOS.MIDRIGHT),
	txt("I know we've started off on a terrible foot, and that you have every reason to despise me.", KME.AWW),
	txt("I know you have gone through centuries of living, with all the memories and experience that comes with.", KME.AWW),
	txt("I know that I have spent far too long in one place, too afraid to leave.", KME.AWW),
	txt("But at the end of the day, we're both children!", KME.LOVEY),
	txt("We can still grow, we can still change! We have the whole world ahead of us, just waiting to be seen!", KME.AWW),
	txt("We can start to truly live!", KME.CRY),
	txt("And more than anything... I want to live with you.", KME.CRY),
	txt("I love you, Mokou!!", KME.CRYSMILE),
	
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(300, MOKOU.DEF, SPRITEPOS.HIDDEN, s_black),
	
	//, function() {music_set(mus.null)}),	
	
	ntxt(200, u, u, s_fullmoon2, function() {music_set(mus.moonkiss)}),
	
	ntxt(0, KME.CRY, SPRITEPOS.MIDRIGHT),
	ntxt(80, MOKOU.SAD, SPRITEPOS.MIDLEFT),
	
	
	
	ptxt(),
	txt("In a flash, the fire stopped.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("Mokou stayed in place, looking down."),
	txt("And then... she sighed."),
		
	txt("...", MOKOU.SAD, u, u, function() {textbox_set_type(global.textzpix)}),
	txt("Kaguya--", MOKOU.SADSMILE),
	txt("I had no idea you could be so amazing!", MOKOU.CRYLAUGH),
	txt("...", KME.AWW),
	txt("You're right... it's time for a change.", MOKOU.DEF),
	txt("In 1300 years, I've lived countless lives. Most of them were bitter, lonely. They came and went, and I wanted nothing more than to end it all.", MOKOU.SADSMILE),
	txt("But now, I don't feel that way. If only for a little longer, I want to cherish this life. ", MOKOU.DEF),	
	txt("...The life I'm starting with you.", MOKOU.LOVEY),
	txt("Mokou...", KME.LOVEY),
	txt("...", MOKOU.SADSMILE),
	txt("Can I kiss you?", MOKOU.LOVEY),
	txt("...", KME.FUFUFU),
	txt("Not before I kiss you.", KME.FUFUFU),
	
	
	//CG OR BIG OL DESCRIPTION OF KISS GOES HERE
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(00, MOKOU.DEF, SPRITEPOS.HIDDEN),
	ptxt(),
	txt("Without giving myself time for doubt, I closed my eyes and leaned forward.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("And then we were together."),
	//MORE DESCRIPTION

	txt("Despite all the insults and screams that had come from Mokou's lips... they were so soft."),
	txt("And for the first time ever, I could truly feel her heartbeat. It felt so powerful, yet... oddly hollow."),
	txt("A body that had not changed in over 1000 years now seemed unrecognizable."),
	//MOAR DESCRIPTION
	
	ptxt(),
	txt("Mokou seemed stiff at first, as if she didn't know how to properly move."),
	txt("...Not to say that I knew what I was doing either."),
	txt("For a moment my hands searched for a proper place to stay, before I settled on wrapping my arms around her waist."),
	txt("Mokou laid a hand on my chest and another on my shoulder, and I simply let my fingers run through her silky hair-- the hair that, only a month ago, I would want to rip off her scalp."),
	
	ptxt(),
	txt("We settled and then stayed there, leaning into each other more and more."),
	txt("How long was a kiss supposed to last? I did not know, but ours was certainly rather long."),
	txt("It ended all too soon, and we opened our eyes once more."),
	
	ptxt(),
	//prob more text here
	
	ntxt(0, KME.LOVEY, SPRITEPOS.MIDRIGHT),
	ntxt(100, MOKOU.LOVEY, SPRITEPOS.MIDLEFT, s_fullmoon2),
	
	txt("Mokou's eyes were so... content. Like flawed rubies that still shined with perfection."),
	txt("How could she smile so beautifully, after all those centuries of tears?"),
	txt("As soon as I thought that, Mokou stiffened up, and moved back a little. Once again, we were separate."),
	txt("But I kept hold of Mokou's hand-- soft, yet calloused from millions of invisible wounds."),
	
	txt("...", MOKOU.LOVEYSAD, u, u, function() {textbox_set_type(global.textzpix)}),
	txt("Is this love?", MOKOU.LOVEYSAD),
	txt("It feels like it, but...", MOKOU.LOVEYSAD),
	txt("What if it's just desperation? What if we're just two fools who are scared of being lonely forever?", MOKOU.SADSMILE),
	txt("...Maybe so.", KME.AWW),
	txt("But whether or not that's where it started...", KME.AWW),
	txt("No matter the origin, I believe we can learn to truly love.", KME.YAY),
	txt("In a way, we're lucky. We have all of eternity to figure it out.", KME.FUFUFU),
	txt("Guess so.", MOKOU.YAY),
	txt("...", MOKOU.LOVEYSAD),	
	ntxt(0, KME.AWW, SPRITEPOS.MIDRIGHT),
	txt("I'm... scared, honestly.", MOKOU.LOVEYSAD),
	txt("This feeling might seem like forever, but... forever is only a moment.", MOKOU.NEUTRAL),
	txt("We'll change and change until we're unrecognizable, and drift apart.", MOKOU.NEUTRAL),
	txt("Maybe we'll get back together, then be back at each other's throats within a few hundred years.", MOKOU.NEUTRAL),
	txt("Friends will come and go, and we'll have no choice but to move on. We'll eventually see the world fall apart before our eyes.", MOKOU.SAD),
	txt("And when it's all over, it'll only be us, floating in an endless void and losing our minds.", MOKOU.SAD),
	txt("We'll have nothing.", MOKOU.SAD),
	txt("...", KME.CRY),
	txt("...No, Mokou.", KME.CRY),
	txt("We'll have each other.", KME.CRYSMILE),
	ntxt(0, KME.DEF, SPRITEPOS.HIDDEN),
	ntxt(69, MOKOU.DEF, SPRITEPOS.HIDDEN),
	
	ptxt(),
	txt("Mokou changed then. She went deathly still, and her eyes seemed to lose mine.", u, u, u, function() {textbox_set_type(global.textnvl)}),
	txt("Though only an arm's length from me, she felt a million years away."),
	txt("Then Mokou looked into my eyes, and she began to quiver. Despite her best efforts, tears streaked down her face."),
	//moar description here?
	txt("Without thinking, I brought a hand to her cheek, for a light caress that I couldn't imagine doing even yesterday."),
	ptxt(),
	txt("But before it reached, I was in her arms."),
	txt("Her shoulders heaved with each sob that resounded through the sky. As if afraid that I would crumble to dust, she held on as tight as she could."),
	txt("Stunned by the sudden embrace, I simply froze. Those three words I wanted to say were stuck in my throat."),
	txt("But in the back of my mind, I knew no words would be enough-- all I could do was return the favor."),
	txt("So I hugged Mokou as tight as I could, and cried with all my heart."),
	ptxt(),
	txt("I do not know how long we stayed there-- seconds, minutes, or even hours. But it did not matter. However long this moment may have lasted..."),
	txt("It was forever."),
	
	txt("#END OF KAGUYAXMOKOU STORY |w300 ", u, u, s_black, function() {textbox_set_type(global.textzpix)}),
	
	
	
	
	]
	
	endevent = function() {room_goto(TITLE);
		var dude = file_text_open_write("you've won again.kotohime2");
		file_text_write_string(dude, "these files brought to you by aeon")
		file_text_close(dude);
	};
	
	//endevent = textbox_create(txt_end, global.textzpix, false);
}




